# -*- coding: utf-8 -*-
"""acesse_a_tabela_dvdrental.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10SGpP1TQ0iq3E7EHARmRaGw2ox_0Qk-f
"""

import psycopg2 as pg2
import pandas as pd

conn = pg2.connect(host='localhost', port=5432, dbname='dvdrental',
                  user='postgres', password='senha')
cur = conn.cursor()
cur.execute('SELECT * FROM actor')
conn.commit()
data = cur.fetchall()
colnames = [desc.name for desc in cur.description]

cur.close()
conn.close()

df = pd.DataFrame(data, columns=colnames)
df.head()
