# -*- coding: utf-8 -*-
"""conecte_o_python_no_postgresql_usando_psycopg2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e9dSY3cZxOErB3vf9_poonlntN6ImMaD
"""

!pip install psycopg2

import psycopg2 as pg2
import pandas as pd

conn = pg2.connect(host='localhost', port=5432, dbname='demo',
                   user='postgres', password='senha')

cur = conn.cursor()

cur.execute("SELECT * FROM ticket_flights")

conn.commit()

data = cur.fetchall()

cur.close()
conn.close()

data

df = pd.DataFrame(data)

df.head()

col_names = ['ticket_no', 'flight_id', 'fare_conditions', 'amount']

df = pd.DataFrame(data, columns=col_names)
df.head()
