# -*- coding: utf-8 -*-
"""junte_tabelas_agregacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I5rhhaQ7Qe08f-n7qLOdCYJMN8nfPxEW
"""

import psycopg2 as pg2
import pandas as pd

conn = pg2.connect(host='localhost', port=5432, dbname='dvdrental',
                  user='postgres', password='euestouformadanafaculdade')
cur = conn.cursor()

cur.execute('''SELECT * FROM film AS x
LEFT JOIN film_category AS y
ON x.film_id = y.film_id
LEFT JOIN category AS z
ON y.category_id = z.category_id;
''')

conn.commit()
data = cur.fetchall()
colnames = [desc.name for desc in cur.description]
cur.close()
conn.close()

df = pd.DataFrame(data, columns=colnames)
df.head()

df.shape

df[['name', 'rental_duration', 'rental_rate', 'length',
    'replacement_cost']].groupby('name').mean()

df[['name', 'rental_duration', 'rental_rate', 'length',
    'replacement_cost']].dtypes

df['rental_rate'] = df['rental_rate'].astype(float)
df['replacement_cost'] = df['replacement_cost'].astype(float)

df[['name', 'rental_duration', 'rental_rate', 'length',
    'replacement_cost']].groupby('name').mean().sort_values('rental_duration')

