# -*- coding: utf-8 -*-
"""entenda_a_geometria_do_pca.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hjtGAjd6RsxdL6qGZWA7iyhK0ePMO_aw
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.tree import DecisionTreeClassifier

from sklearn.decomposition import PCA
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, ConfusionMatrixDisplay
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

df = pd.read_feather('notas.ftr')

df.head()

variaveis = ['por_p1', 'por_p2']

fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(1, 1, 1)

ax.set_aspect('equal', 'box')
ax.set(xlim=(-1, 11), ylim=(-1, 11))

plt.scatter(x=df[variaveis[0]], y=df[variaveis[1]])

df[variaveis].cov()

"""### Transformações lineares"""

fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(1, 1, 1)

ax.set_aspect('equal', 'box')
ax.set(xlim=(-4, 11), ylim=(-4, 11))

plt.scatter(x=df[variaveis[0]], y=df[variaveis[1]])

m = np.array([[0.5, 0.5],
              [-1, 1]])

df_rot = np.matmul(m, df[variaveis].to_numpy().transpose())
plt.scatter(df_rot[0, :], df_rot[1, :])

plt.xlabel('Desempenho geral do aluno')
plt.ylabel('Evolução do aluno')

pd.DataFrame(df_rot.transpose()).corr()

fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(1, 1, 1)

ax.set_aspect('equal', 'box')
ax.set(xlim=(-4, 15), ylim=(-4, 15))

m = np.array([[0.69245036, -0.72146552],
              [0.72146552, 0.69245036]])

df_rot = np.matmul(m, df[variaveis].to_numpy().transpose())

plt.scatter(x=df[variaveis[0]], y=df[variaveis[1]])
plt.scatter(df_rot[0, :], df_rot[1, :])

pd.DataFrame(df_rot.transpose()).corr()

fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(1, 1, 1)

X = df[variaveis].apply(lambda var: (var-var.mean())/ var.std(), axis=0)

ax.scatter(x = X.iloc[:, 0], y = X.iloc[:, 1])

xmin = -3
xmax = 3
ymin = -3
ymax = 3

ax.set_aspect('equal', 'box')
ax.set(xlim=(xmin, xmax), ylim=(ymin, ymax));

autovet=np.array([[0.69245036, -0.72146552],
                  [0.72146552, 0.69245036]])

ax.arrow(0, 0, autovet[0, 0], autovet[1, 0],
         head_width=0.25,
         head_length=0.1,
         fc='g', ec='g',
         length_includes_head=True)
ax.arrow(0, 0, autovet[0,1], autovet[1,1],
         head_width=0.25,
         head_length=0.1,
         fc='g', ec='g',
         length_includes_head=True)