# -*- coding: utf-8 -*-
"""barra_de_progresso_usando_tqdm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zvlGQQZ7t305CIiBHpzilLjjro8P3GgO
"""

import pandas as pd

results = pd.read_html("https://www.basketball-reference.com/leagues/NBA_2021_games-january.html")[0]

colunas = {
    'Date': 'Data',
    'Start (ET)': 'Horário',
    'Visitor/Neutral': 'Time Visitante',
    'PTS': 'PTS Visitante',
    'Home/Neutral': 'Time Casa',
    'PTS.1': 'PTS Casa',
    'Unnamed: 6': 'A',
    'Unnamed: 7': 'B',
    'Attend.': 'Público',
    'Notes': 'Anotações'
}

results.rename(columns=colunas, inplace=True)

results['Data 1'] = results['Data']
results['Data 2'] = results['Data']
results['Data 3'] = results['Data']
results['Data 4'] = results['Data']
results['Data 5'] = results['Data']
results['Data 6'] = results['Data']

df_datas = results[['Data', 'Data 1', 'Data 2', 'Data 3', 'Data 4', 'Data 5', 'Data 6']]
df_datas

!pip install tqdm

from tqdm import tqdm
tqdm.pandas() # Dentro do pandas, utilizar o tqdm

df_datas_maior = pd.concat([df_datas] * 100, ignore_index=True)
df_datas_maior

df_datas_maior.progress_apply(lambda x: pd.to_datetime(x), axis=0)

df_datas_maior.progress_apply(lambda x: pd.to_datetime(x), axis=1)

"""### Exemplos de uso do tqdm

#### Loop for com uma lista
"""

import time

my_list = range(100) # Exemplo de lista

# Criando a barra de progresso
for item in tqdm(my_list, desc="Processando lista"):
   time.sleep(0.1) # Simulando alguma operação demorada

"""#### Loop while com uma condição"""

# Exemplo de loop while com contador

counter = 0
total_iterations = 100

# Criando a barra de progresso
with tqdm(total=total_iterations, desc="Processando loop while") as pbar:
  while counter < total_iterations:

    # Simulando alguma operação demorada
    time.sleep(0.1)
    counter += 1
    pbar.update(1) # Atualizando a barra de progresso

"""#### Outro exemplo de loop for usando um dicionário"""

# Exemplo de dicionário

my_dict = {'a': 1, 'b': 2, 'c': 3}
# Criando a barra de progresso

for key in tqdm(my_dict.keys(), desc="Processando dicionário"):
  # Simulando alguma operação demorada
  time.sleep(0.1)