# -*- coding: utf-8 -*-
"""conheca_as_funcoes_de_janela_movel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JMI5bN7OiQPznmDm46lo7YDGlB1x5Tuk
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# %matplotlib inline
sns.set()

sensor_data = pd.read_csv('/content/sensor-data.csv')
sensor_data.head()

# Verificando dados duplicados
sensor_data[sensor_data.time.duplicated(keep=False)]

# Dropar todas as duplicatas, mantendo apenas a primeira linha

sensor_data = sensor_data.drop_duplicates(subset='time', keep='first')
sensor_data[sensor_data['time'] == '2015-08-16 05:08:23']

sensor_data = (sensor_data.assign(time=pd.to_datetime(sensor_data.time))
               .set_index('time'))
sensor_data.head()

# Vendo ao longo do tempo como a captura desses sensores vai oscilando

fig, (ax1, ax2, ax3, ax4, ax5, ax6) = plt.subplots(6, figsize=(20,20))

ax1.plot(sensor_data.index, sensor_data['power'])
ax2.plot(sensor_data.index, sensor_data['temp'])
ax3.plot(sensor_data.index, sensor_data['humidity'])
ax4.plot(sensor_data.index, sensor_data['light'])
ax5.plot(sensor_data.index, sensor_data['CO2'])
ax6.plot(sensor_data.index, sensor_data['dust'])
plt.show()

sensor_data['dust'].head(10)

"""### Média Móvel"""

# Janela 2
sensor_data['dust'].head(10).rolling(2).mean()

print('Média Móvel de janela 2 da 1ª linha:', (27.09 + 27.80) / 2)
print('Média Móvel de janela 2 2 da 2ª linha:', (34.50 + 27.09) / 2)

# Janela 10
sensor_data['dust'].head(20).rolling(10).mean()

sensor_data.rolling(600).mean().plot()

sensor_data.dust.rolling(600).mean().plot()

plt.figure(figsize=(18, 8))
sensor_data.humidity.plot(label='original')
sensor_data.humidity.rolling(250).mean().plot(label='Média Móvel de Janela 250')
plt.legend()
plt.ylim(25, 48)
sns.despine()

"""### Downsampling"""

sensor_data

sensor_data.resample('60s', closed='right').mean()

"""### Upsampling"""

sensor_data

sensor_data.head(20).resample('10s').mean()

sensor_data.head(10).resample('10s').ffill()

sensor_data.head(10).resample('10s').bfill()

sensor_data.head(10).resample('10s').mean().interpolate(method='time')

"""### Shift"""

sensor_data['dust_1'] = sensor_data.dust.shift(+1)
sensor_data[['dust', 'dust_1']].head(15)

sensor_data[['dust', 'dust_1']].head(15).corr()