# -*- coding: utf-8 -*-
"""for_vs_list_comprehension.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d4w__apVEUrkm4We5AEikE-21xAdaErO
"""

import pandas as pd
import numpy as np

df = pd.DataFrame({"A": np.arange(10, 101, 10),
                   "B": np.arange(1, 11, 1)})

df

df['A'] + df['B']

"""### Diferença entre `for` e `list comprehension`"""

for a in df['A']:
  print(a)

[print(a) for a in df['A']]

# zip permite concatenar duas colunas (conjuntos)

list(zip(df['A'], df['B']))

# Utilizando o zip no for para percorrer os valores das duas listas
for a, b in zip(df['A'], df['B']):
  print(a, b)

# Fazendo o mesmo com o list comprehension
[print(a, b) for a, b in zip(df['A'], df['B'])]

"""### Desafio 1: somar A + B apenas quando B for par"""

# Com for
for a, b in zip(df['A'], df['B']):
  if b % 2 == 0:
    print(a + b)

# Com list comprehension
[print(a + b) for a, b in zip(df['A'], df['B']) if b % 2 == 0]

"""### Desafio 2: somar A + B apenas quando B for par e onde for ímpar, zerar"""

# Com for

for a, b in zip(df['A'], df['B']):
  if b % 2 == 0:
    print(a + b)
  else:
    print(0)

# Com list comprehension

[a + b if b % 2 == 0 else 0 for a, b in zip(df['A'], df['B'])]