# -*- coding: utf-8 -*-
"""method_chaining_encadeamento_de_metodos_parte_II.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q01JL3Sb_scDdkr6HEnCkpQCx6_mj7Qx
"""

import pandas as pd
import os

def vencedor(df):
  if df['PTS Visitante'] < df["PTS Casa"]:
    df["Ganhador"] = "Casa"
  elif df['PTS Visitante'] > df["PTS Casa"]:
     df["Ganhador"] = "Visitante"

  return df

results = pd.read_html("https://www.basketball-reference.com/leagues/NBA_2021_games-january.html")[0]

colunas = {
    'Date': 'Data',
    'Start (ET)': 'Horário',
    'Visitor/Neutral': 'Time Visitante',
    'PTS': 'PTS Visitante',
    'Home/Neutral': 'Time Casa',
    'PTS.1': 'PTS Casa',
    'Unnamed: 6': 'A',
    'Unnamed: 7': 'B',
    'Attend.': 'Público',
    'Notes': 'Anotações'
}

results_renomeado = results.rename(columns=colunas)
results_renomeado["Data"] = pd.to_datetime(results_renomeado.Data)
results_renomeado_data = results_renomeado.set_index('Data')
results_renomeado_data_cols = results_renomeado_data.drop(["Horário", "A", "B", "Público", "Anotações", "LOG"], axis=1)
results_renomeado_data_cols["PTS Total"] = results_renomeado_data_cols["PTS Visitante"] + results_renomeado_data_cols["PTS Casa"]
results_renomeado_data_cols = results_renomeado_data_cols.apply(vencedor, axis=1)
results_renomeado_data_cols.Ganhador.value_counts(normalize=True)