# -*- coding: utf-8 -*-
"""method_chaining_encadeamento_de_metodos_parte_I.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vcxmCFatl9gycsXDbuC0VLpPSEJWJxuJ
"""

import pandas as pd
import os

path = 'dados/nba_2021.csv'
os.makedirs('/content/dados', exist_ok=True)

results = pd.read_html("https://www.basketball-reference.com/leagues/NBA_2021_games-january.html")[0]
results.to_csv(path)
results.head()

colunas = {
    'Date': 'Data',
    'Start (ET)': 'Horário',
    'Visitor/Neutral': 'Time Visitante',
    'PTS': 'PTS Visitante',
    'Home/Neutral': 'Time Casa',
    'PTS.1': 'PTS Casa',
    'Unnamed: 6': 'A',
    'Unnamed: 7': 'B',
    'Attend.': 'Público',
    'Notes': 'Anotações'
}

results_renomeado = results.rename(columns=colunas)
results_renomeado.head()

# Criando um noov dataframe chamado result_renomeado com as colunas renomeadas.
# Pra cada coluna, fizemos um dicionário

# Mudando o formato da coluna "Data" para Datetime

results_renomeado["Data"] = pd.to_datetime(results_renomeado.Data)
results_renomeado.head()

# Criando um novo dataframe a partir de results_renomeado, setando a data como
# index. Quando fazemos visualizações e outras coisas do tipo, facilita muito
# ter a data como índice

results_renomeado_data = results_renomeado.set_index('Data')
results_renomeado_data.head()

# Dropando algumas colunas desnecessárias

results_renomeado_data_cols = results_renomeado_data.drop(["Horário", "A", "B", "Público", "Anotações", "LOG"], axis=1)
results_renomeado_data_cols.head()

# Nesse mesmo dataframe, estamos criando uma nova coluna com o total de pontos.

results_renomeado_data_cols["PTS Total"] = results_renomeado_data_cols["PTS Visitante"] + results_renomeado_data_cols["PTS Casa"]
results_renomeado_data_cols.head()

# Criando uma função para determinar o vencedor do jogo. Para isso, criamos uma
# flag marcando quem foi o ganhador

def vencedor(df):
  if df['PTS Visitante'] < df["PTS Casa"]:
    df["Ganhador"] = "Casa"
  elif df['PTS Visitante'] > df["PTS Casa"]:
     df["Ganhador"] = "Visitante"
  # O basquete é um esporte dividido em quatro períodos de 10 minutos cada
   # (na FIBA), e 12 na NBA, mas o empate não é uma opção. Se o jogo terminar
   # com placar igualado ao final do tempo regulamentar, são adicionados tempos
   # extras de 5 minutos (chamados de prorrogação ou "overtime") até que uma das
   # equipes vença

  return df

results_renomeado_data_cols = results_renomeado_data_cols.apply(vencedor, axis=1)
results_renomeado_data_cols.head()

# Calcular o percentual de jogos que o Time da Casa venceu.

results_renomeado_data_cols.Ganhador.value_counts(normalize=True)