# -*- coding: utf-8 -*-
"""method_chaining_encadeamento_de_metodos_parte_III.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fnCNGo7AVU5uikT65o8TsKo8a4954hc9
"""

import pandas as pd
import os
import numpy as np

def vencedor(df):
  df['Ganhador'] = np.where(df['PTS Visitante']<df['PTS Casa'], 'Casa', 'Visitante')

  return df

results = pd.read_html("https://www.basketball-reference.com/leagues/NBA_2021_games-january.html")[0]

colunas = {
    'Date': 'Data',
    'Start (ET)': 'Horário',
    'Visitor/Neutral': 'Time Visitante',
    'PTS': 'PTS Visitante',
    'Home/Neutral': 'Time Casa',
    'PTS.1': 'PTS Casa',
    'Unnamed: 6': 'A',
    'Unnamed: 7': 'B',
    'Attend.': 'Público',
    'Notes': 'Anotações'
}

results_novo = (results.rename(columns=colunas)
      .assign(Data=lambda x: pd.to_datetime(x.Data))
      .set_index("Data")
      .drop(["Horário", "A", "B", "Público", "Anotações", "LOG"], axis=1)
      .assign(Total=lambda x: x['PTS Visitante'] + x['PTS Casa'])
      .pipe(vencedor))

results_novo.head()