# -*- coding: utf-8 -*-
"""metodo_apply_axis_0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BPFxHXP5IyOOICe6T9n2FfY69P5VW1S9
"""

import pandas as pd

results = pd.read_html("https://www.basketball-reference.com/leagues/NBA_2021_games-january.html")[0]

colunas = {
    'Date': 'Data',
    'Start (ET)': 'Horário',
    'Visitor/Neutral': 'Time Visitante',
    'PTS': 'PTS Visitante',
    'Home/Neutral': 'Time Casa',
    'PTS.1': 'PTS Casa',
    'Unnamed: 6': 'A',
    'Unnamed: 7': 'B',
    'Attend.': 'Público',
    'Notes': 'Anotações'
}

results.rename(columns=colunas, inplace=True)

# Criando várias colunas com "datas", apenas para exemplificar como seria se
# tivéssemos um dataframe nesse estilo

results['Data 1'] = results['Data']
results['Data 2'] = results['Data']
results['Data 3'] = results['Data']
results['Data 4'] = results['Data']
results['Data 5'] = results['Data']
results['Data 6'] = results['Data']

df_datas = results[['Data', 'Data 1', 'Data 2', 'Data 3', 'Data 4', 'Data 5', 'Data 6']]
df_datas

df_datas.dtypes

"""### Transformando as variáveis em datetime utilizando o `for`"""

df_datas = df_datas.reset_index(drop=True)

for col in df_datas.columns:
  df_datas[col] = pd.to_datetime(df_datas[col])

df_datas

df_datas.dtypes

"""### Utilizando o `assign()`"""

df_datas = results[['Data', 'Data 1', 'Data 2', 'Data 3', 'Data 4', 'Data 5', 'Data 6']]
df_datas.dtypes

df_datas = df_datas.assign(
    Data=lambda x: pd.to_datetime(x['Data']),
    Data_1=lambda x: pd.to_datetime(x['Data 1']),
    Data_2=lambda x: pd.to_datetime(x['Data 2']),
    Data_3=lambda x: pd.to_datetime(x['Data 3']),
    Data_4=lambda x: pd.to_datetime(x['Data 4']),
    Data_5=lambda x: pd.to_datetime(x['Data 5']),
    Data_6=lambda x: pd.to_datetime(x['Data 6'])
)

df_datas

df_datas.dtypes

"""### Utilizando o `apply()`"""

df_datas = results[['Data', 'Data 1', 'Data 2', 'Data 3', 'Data 4', 'Data 5', 'Data 6']]
df_datas.dtypes

df_datas = df_datas.apply(lambda x: pd.to_datetime(x), axis=0)
df_datas

df_datas.dtypes

"""### Avaliando a diferença de performance entre `axis=0` e `axis=1`"""

df_datas = results[['Data', 'Data 1', 'Data 2', 'Data 3', 'Data 4', 'Data 5', 'Data 6']]
df_datas.dtypes

# Commented out IPython magic to ensure Python compatibility.
# %timeit df_datas.apply(lambda x: pd.to_datetime(x), axis=0)
# %timeit df_datas.apply(lambda x: pd.to_datetime(x), axis=1)

"""### E se tivermos mais colunas do que linhas?"""

df_datas.head(2)

# Commented out IPython magic to ensure Python compatibility.
# %timeit df_datas.head(2).apply(lambda x: pd.to_datetime(x), axis=0)
# %timeit df_datas.head(2).apply(lambda x: pd.to_datetime(x), axis=1)