# -*- coding: utf-8 -*-
"""mostre_o_dataframe_usando_o_style.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XwLRB1gtSZm2NesnH-s8iaxCClyT_RJ-
"""

import pandas as pd

df = pd.read_csv('/content/dados.csv')
df.head()

# Rodando um modelo de regressão logística rapidamente, selecionando apenas
# algumas colunas
import statsmodels.api as sm

cols = [
    'qtd_filhos', 'idade', 'tempo_emprego', 'qt_pessoas_residencia',
    'possui_email'
]

# Definindo as variáveis dependentes e independentes
Xtrain = df[cols]
ytrain = df[['mau']]

log_reg = sm.Logit(ytrain, Xtrain).fit()

log_reg.summary()

log_reg.params.to_frame()

(log_reg.params.to_frame()
        .reset_index()
        .rename(columns={'index': 'Variável', 0:'coef'})
        .sort_values('coef', ascending=False)
        .style.bar(color=['grey', 'lightblue'], align='zero')
        .format(precision=2))

from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv('/content/dados.csv')
rf = RandomForestClassifier()

cols = [
    'qtd_filhos', 'idade', 'tempo_emprego', 'qt_pessoas_residencia',
    'possui_email', 'possui_fone', 'possui_fone_comercial'
]

rf.fit(df[cols], df['mau'])

print('Feature Importances: ', rf.feature_importances_)
print('Variáveis: ', cols)

(pd.DataFrame({
    'Variável': cols,
    'Feature importances': rf.feature_importances_
})
    .sort_values('Feature importances', ascending=False)
    .style.bar(color=['grey', 'lightblue'], align='zero')
    .format(precision=2))
