# -*- coding: utf-8 -*-
"""use_o_metodo_.apply().ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16T9JmmTGNjy_hRKGB07Nf_ZIStnrVyOF
"""

import pandas as pd
import numpy as np

df = pd.DataFrame({'A': np.arange(10, 101, 10),
                   'B': np.arange(1, 11, 1)})

df.head()

df['A'] + df['B']

df.apply(lambda x: print(x), axis=0)

df.apply(lambda x: print(x), axis=1)

# Utilizando o apply() é possível somar as duas colunas. Usamos o axis=1 para
# somar linha a linha
df.apply(lambda x: x['A'] + x['B'], axis=1)

df['B'] % 2 == 0

"""### Aplicando `apply()` com if-else


"""

df.apply(lambda x: x['A'] + x['B'] if x['B'] % 2 == 0 else 0, axis=1)

"""### Aplicar uma função definida por nós mesmos (UDF - user defined function)"""

def soma_se_par(df):
  if (df['B'] % 2 == 0):
    return df['B'] + df['A']
  else:
    return 0

df.apply(soma_se_par, axis=1)

"""### Comparando a performance do `list comprehension `com o` apply()`"""

# Commented out IPython magic to ensure Python compatibility.
# %timeit [a + b if b % 2 == 0 else 0 for a, b in zip(df['A'], df['B'])]
# %timeit df.apply(soma_se_par, axis=1)

# Avaliando a performance com um dataframe maior

df_maior = pd.concat([df] * 5000, ignore_index=True)
df_maior

# Commented out IPython magic to ensure Python compatibility.
# %timeit [a + b if b % 2 == 0 else 0 for a, b in zip(df_maior['A'], df_maior['B'])]
# %timeit df_maior.apply(soma_se_par, axis=1)

df['B']** 2 + df['A']

df.apply(lambda x: x['B']** 2 + x['A'], axis=1)

# Commented out IPython magic to ensure Python compatibility.
# %timeit df['B']** 2 + df['A']
# %timeit df.apply(lambda x: x['B']** 2 + x['A'], axis=1)