# -*- coding: utf-8 -*-
"""conheca_o_k_fold_parte_II.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14NS81QLxvRF28qhgTSCOkvYzt2V-IiMB

### K-fold com holdout
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, roc_auc_score

pg1 = pd.read_csv('pg1.csv')
pg1.head()

X = pd.get_dummies(pg1.drop(columns=['island', 'species']), drop_first=True)
y = pg1.species

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2360873)

clf = DecisionTreeClassifier(random_state=2360873)
caminho = clf.cost_complexity_pruning_path(X_train, y_train)
ccp_alphas, impurities = caminho.ccp_alphas, caminho.impurities

ccp_alphas = np.unique(ccp_alphas)
ccp_alphas

"""### GridSearchCV"""

clf = DecisionTreeClassifier(random_state=2360873)
clf

grid_parametros = {'ccp_alpha': ccp_alphas}
grid_parametros

grid = GridSearchCV(estimator=clf, param_grid=grid_parametros, cv=15, verbose=100)
grid.fit(X_train, y_train)

grid

resultados = pd.DataFrame(grid.cv_results_)
resultados.head()

grid.best_index_

grid.best_estimator_

grid.best_params_

grid.best_score_

"""### Melhor árvore"""

melhor_ccp = resultados.iloc[grid.best_index_, 4]
clf = DecisionTreeClassifier(ccp_alpha=melhor_ccp, random_state=2360873)
clf.fit(X_train, y_train)

clf.score(X_test, y_test)