# -*- coding: utf-8 -*-
"""prepare_a_base_parte_I.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yXuIqpZXNpAmxrQmsgC98dBEtgEnZ_8o
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

pg = sns.load_dataset('penguins')
print('Quantidade de linhas:', pg.shape[0])
print('Quantidade de colunas/variáveis:', pg.shape[1])

pg.head()

# Verificando possíveis dados faltantes
pg.isna().sum()

"""### Descritiva inicial"""

# Gráfico que divide as espécies em "clusters"
sns.pairplot(pg, hue='species')

"""### Limpando a preparando a base"""

# Verificando os registros missing que bill_depth_mm tem
pg[pg['bill_depth_mm'].isna()]

pg1 = pg[~pg['bill_depth_mm'].isna()].copy()

sns.set_theme(style='ticks')
sns.boxplot(data=pg, x='species', hue='sex', y='bill_length_mm')

pg2 = pg1[~pg1['sex'].isna()]
print('Quantidade de linhas:', pg2.shape[0])
print('Quantidade de colunas/variáveis:', pg2.shape[1])

pg2.isna().sum()

y0 = pg2.sex
X0 = pd.get_dummies(pg2.drop(columns=['sex']), drop_first=True)

X0_train, X0_test, y0_train, y0_test = train_test_split(X0, y0)
X0.head()

"""### Construindo a árvore para classificar `sex`"""

clf0 = DecisionTreeClassifier(random_state=42)
path = clf0.cost_complexity_pruning_path(X0_train, y0_train)
ccp_alphas, impurities = path.ccp_alphas, path.impurities

clfs0 = []

for ccp_alpha in ccp_alphas:

    clf0 = DecisionTreeClassifier(random_state=2360873, ccp_alpha=ccp_alpha).fit(X0_train, y0_train)
    clfs0.append(clf0)

train_scores = [clf0.score(X0_train, y0_train) for clf0 in clfs0]
test_scores = [clf0.score(X0_test, y0_test) for clf0 in clfs0]

fig, ax = plt.subplots()
ax.set_xlabel('Alpha')
ax.set_ylabel('Acurácia')
ax.set_title('Acurácia x alpha do conjunto de dados de treino e teste')
ax.plot(ccp_alphas, train_scores, marker='o', label='treino',
        drawstyle='steps-post')
ax.plot(ccp_alphas, test_scores, marker='o', label='teste',
        drawstyle='steps-post')
ax.legend()
plt.show()

ind_melhor_arvore = len(test_scores) - test_scores[::-1].index(max(test_scores)) - 1
melhor_arvore = clfs0[ind_melhor_arvore]
melhor_arvore

prever = pd.get_dummies(pg1.drop(columns=['sex']), drop_first=True)
prever_sex = prever[pg1['sex'].isna()]

imputacao_sex = melhor_arvore.predict(prever_sex)
imputacao_sex

pg1.loc[pg1['sex'].isna(), 'sex'] = imputacao_sex

print(pg1.shape)
pg1.isna().sum()

pg1.to_csv('pg1.csv', index=False)

