# -*- coding: utf-8 -*-
"""implemente_transformacoes_lineares_no_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/104N27t7xLDt9HbADGS3BuniIVbeOuk9K
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

# %matplotlib inline

# Definindo e configurando figura e sistemas de eixos
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
ax.set_aspect('equal', 'box')
ax.set(xlim=(0, 11), ylim=(0, 11))

# Gerando os dados
np.random.seed(123)

p1 = np.random.random(10) *10
p1[p1 > 10] = 10
p1[p1 < 0] = 0

p2 = p1 + np.random.normal(0,1,10)
p2[p2 > 10] = 10
p2[p2 < 0] = 0
p2

# Gerando o dataframe
df = pd.DataFrame({'p1': p1, 'p2': p2})
#Plotando
plt.scatter(x = df.p1, y=df.p2);

# Calculando média e evolução
df['média'] = df.mean(axis=1)
df['evolução'] = df.p2 - df.p1
df.style.format(precision=1, decimal=',')

# método style do Pandas dá diversos recursos, inclusive escolher o separador do
# decimal

"""### Transformação linear"""

#Definindo figura e configurando eixos
fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(1, 1, 1)

xmin = -15
xmax = 15
ymin = -15
ymax = 15

# ax.axis('equal')
ax.set_aspect('equal', 'box')
ax.set(xlim=(xmin, xmax), ylim=(ymin, ymax))

lista_xticks = list(range(int(xmin), int(xmax) + 1))
ticksx = ax.set_xticks(lista_xticks)
labelsx = ax.set_xticklabels(lista_xticks, fontsize='large')

lista_yticks = list(range(int(ymin), int(ymax) + 1))
ticksy = ax.set_yticks(lista_yticks)
labelsy = ax.set_yticklabels(lista_yticks, fontsize='large')

#Matriz de transformação
m = np.array([[0.5, 0.5],
              [-1, 1]])

# Vetores coluna da matriz de transformação
ax.arrow(0, 0, m[0, 0], m[1, 0],
         head_width=0.25,
         head_length=0.1,
         fc='g', ec='g',
         length_includes_head=True)

ax.arrow(0, 0, m[0, 1], m[1, 1],
         head_width=0.25,
         head_length=0.1,
         fc='r', ec='r',
         length_includes_head=True)


# Linhas horizontais e verticais de referência
ax.axvline(0, linewidth=0.5, linestyle='--')
ax.axhline(0, linewidth=0.5, linestyle='--')

#Transformação linear
df_rot = np.matmul(m, df[['p1', 'p2']].to_numpy().transpose())

# Plotar os dados originais
plt.scatter(df['p1'], df['p2'], label='originais')

# Plotar os dados transformados
plt.scatter(df_rot[0, :], df_rot[1, :], label='transformados')

#Legenda
plt.legend()

def transf_lin(m):

    #Definindo figura e configurando eixos
    fig = plt.figure(figsize=(10, 10))
    ax = fig.add_subplot(1, 1, 1)

    xmin = -15
    xmax = 15
    ymin = -15
    ymax = 15

    # ax.axis('equal')
    ax.set_aspect('equal', 'box')
    ax.set(xlim=(xmin, xmax), ylim=(ymin, ymax))

    lista_xticks = list(range(int(xmin), int(xmax) + 1))
    ticksx = ax.set_xticks(lista_xticks)
    labelsx = ax.set_xticklabels(lista_xticks, fontsize='large')

    lista_yticks = list(range(int(ymin), int(ymax) + 1))
    ticksy = ax.set_yticks(lista_yticks)
    labelsy = ax.set_yticklabels(lista_yticks, fontsize='large')

    # Vetores coluna da matriz de transformação
    ax.arrow(0, 0, m[0, 0], m[1, 0],
             head_width=0.25,
             head_length=0.1,
             fc='g', ec='g',
             length_includes_head=True)

    ax.arrow(0, 0, m[0, 1], m[1, 1],
             head_width=0.25,
             head_length=0.1,
             fc='r', ec='r',
             length_includes_head=True)


    #linhas horizontais e verticais de referência
    ax.axvline(0, linewidth=0.5, linestyle='--')
    ax.axhline(0, linewidth=0.5, linestyle='--')

    #Transformação linear
    df_rot = np.matmul(m, df[['p1', 'p2']].to_numpy().transpose())

    # Plotar os dados originais
    plt.scatter(df['p1'], df['p2'], label='originais')

    # Plotar os dados transformados
    plt.scatter(df_rot[0,:], df_rot[1, :], label='rotação')

    #Legenda
    plt.legend(loc='lower right')

t = np.array([[-1, 0],
              [0, -1]])
transf_lin(t)

def translin_v2(m):
    fig = plt.figure(figsize=(10, 10))
    ax = fig.add_subplot(1, 1, 1)

    xmin = -2
    xmax = df.p1.max() * 1.1
    ymin = -2
    ymax = df.p2.max() * 1.1

    ax.axis('equal')
    ax.set_aspect('equal', 'box')
    ax.set(xlim=(xmin, xmax), ylim=(ymin, ymax))

    lista_xticks = list(range(int(xmin), int(xmax)+1))
    ticksx = ax.set_xticks(lista_xticks)
    labelsx = ax.set_xticklabels(lista_xticks, fontsize='large')

    lista_yticks = list(range(int(ymin), int(ymax)+1))
    ticksy = ax.set_yticks(lista_yticks)
    labelsy = ax.set_yticklabels(lista_yticks, fontsize='large')

    ax.axvline(0, linewidth=0.5, linestyle='--')
    ax.axhline(0, linewidth=0.5, linestyle='--')

    ax.arrow(0, 0, m[0, 0], m[0, 1],
             head_width=0.25,
             head_length=0.1,
             fc='g', ec='g',
             length_includes_head=True)

    ax.arrow(0, 0, m[1, 0], m[1, 1],
             head_width=0.25,
             head_length=0.1,
             fc='r', ec='r',
             length_includes_head=True)

    plt.scatter(x = df.p1, y=df.p2, label='originais')
    plt.scatter(x = df['média'], y=df['evolução'], label = 'transformados')

    ax.legend(loc='upper left')

t = np.array([[.5, .5],
              [-1, 1]])
translin_v2(t)

plt.scatter(x=df['média'], y=df['evolução'])