# -*- coding: utf-8 -*-
"""sql_m06_tarefa_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IUV_MvayvpyQ5GxlaigaqaWg0JvI1pjG
"""

import pandas as pd

"""## Query 1

```sql
SELECT id_cliente FROM transacoes
UNION
SELECT id_cliente  FROM cliente;
```
"""

query_01 = pd.read_csv('query_01.csv')
query_01

"""## Query 2

```sql
SELECT transacoes.id_cliente, cliente.nome
FROM transacoes
INNER JOIN cliente
ON transacoes.id_cliente = cliente.id_cliente;
```
"""

query_02 = pd.read_csv('query_02.csv')
query_02

"""## Query 3

```sql
SELECT *
FROM cliente
CROSS JOIN transacoes;
```
"""

query_03 = pd.read_csv('query_03.csv')
query_03

"""## Query 4

```sql
SELECT *
FROM transacoes
LEFT JOIN cliente
ON cliente.id_cliente = transacoes.id_cliente;
```
"""

query_04 = pd.read_csv('query_04.csv')
query_04

"""## Query 5

```sql
SELECT *
FROM transacoes
RIGHT JOIN cliente
ON cliente.id_cliente = transacoes.id_cliente;
```
"""

query_05 = pd.read_csv('query_05.csv')
query_05

