# -*- coding: utf-8 -*-
"""compreenda_a_distancia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ztyONYQGLQZxauqCQF3Jq2NoTCfCVDxp
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

penguins = sns.load_dataset('penguins')
penguins.head()

# Não aceita variáveis strings, nem variáveis missing

penguins.isna().sum()

penguins[penguins.body_mass_g.isna()]

# Eliminando os missing
penguins.dropna(subset=['body_mass_g'], inplace=True)

# Mantendo só as variáveis numéricas no dataset

penguins_quant = penguins.select_dtypes(include='number')
penguins_quant.head()

sns.pairplot(penguins, hue='species')

kmeans = KMeans(n_clusters=3, max_iter=600)
kmeans.fit(penguins_quant)

penguins['grupo'] = kmeans.labels_.astype('str')
sns.pairplot(penguins, hue='grupo')

"""### Padronização"""

padronizador = StandardScaler()
penguins_padronizados = padronizador.fit_transform(penguins_quant)

sns.pairplot(pd.DataFrame(penguins_padronizados))

kmeans.fit(penguins_padronizados)

penguins['grupo'] = kmeans.labels_
sns.pairplot(penguins, hue='grupo')

penguins['grupo'] = kmeans.labels_
sns.pairplot(penguins, hue='species')

pd.crosstab(penguins['species'], penguins['grupo'])

