# -*- coding: utf-8 -*-
"""entenda_como_funciona_o_algoritmo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hZL7sgTCV7TQHwqiPA6adfWGl-CV7MD7
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy.spatial import distance

"""## Gerando os dados"""

# Gerar os dados
np.random.seed(2360873)
x = np.random.normal([1, 2, 3] * 4, .2, 12)
y = np.random.normal([0, 2, 0] * 4, .2, 12)

pontos = pd.DataFrame(np.c_[x,y], columns=['x', 'y'])

pontos

fig = plt.figure(figsize = (6, 6))
ax = fig.add_subplot(1, 1, 1)
ax.scatter(pontos['x'], pontos['y'])

for idx, col in pontos.iterrows():
  ax.annotate(idx, (col['x'], col['y'] + .05) )

"""## Gerando os centroides"""

# Gerar os dados
np.random.seed(2360873)

# Centroides iniciais
centroides = pd.DataFrame(np.array([[1, 1], [2, 0], [3, 1]]), columns = ['x', 'y'])

# Fazer o gráfico dos PONTOS
fig = plt.figure(figsize = (6,6))
ax = fig.add_subplot(1,1,1)
ax.scatter(pontos['x'], pontos['y'])

# Identificar centroides no gráfico
ax.scatter(centroides.x, centroides.y, c=[1, 2, 3], marker='+', s=200, cmap='viridis')

for idx, col in pontos.iterrows():
     ax.annotate(idx, (col['x'], col['y'] + .05))

"""## Classificar os pontos aos centroides mais próximos"""

# Calcula a distância entre os pontos e os centroides
dists = distance.cdist(pontos, centroides, 'euclidean')

# Classifica o ponto no grupo com menor distância ao respectivo centróide
grupo = dists.argmin(1)

dists

grupo

fig = plt.figure(figsize=(6, 6))
ax = fig.add_subplot(1, 1, 1)

ax.scatter(pontos['x'], pontos['y'], c=grupo)
ax.set_aspect('equal', 'box')

ax.scatter(centroides.x, centroides.y, c=[1, 2, 3], marker='+', s=200, cmap='viridis')

for idx, col in pontos.iterrows():
     ax.annotate(idx, (col['x'], col['y'] + .05))

"""## Atualizar os centroides"""

centroides = pontos.groupby(grupo).mean()

fig = plt.figure(figsize = (6, 6))
ax = fig.add_subplot(1, 1, 1)

ax.scatter(pontos['x'], pontos['y'], c=grupo)
ax.set_aspect('equal', 'box')

ax.scatter(centroides.x, centroides.y, c=[1, 2, 3], marker='+', s=200, cmap='viridis')

for idx, col in pontos.iterrows():
     ax.annotate(idx, (col['x'], col['y'] + .05))

dists = distance.cdist(pontos, centroides, 'euclidean')

grupo = dists.argmin(1)

fig = plt.figure(figsize = (6, 6))
ax = fig.add_subplot(1, 1, 1)

ax.scatter(pontos['x'], pontos['y'], c=grupo)
ax.set_aspect('equal', 'box')

ax.scatter(centroides.x, centroides.y, c=[1, 2, 3], marker='+', s=200, cmap='viridis')

for idx, col in pontos.iterrows():
     ax.annotate(idx, (col['x'], col['y'] + .05) )

centroides = pontos.groupby(grupo).mean()

fig = plt.figure(figsize = (6, 6))
ax = fig.add_subplot(1, 1, 1)

ax.scatter(pontos['x'], pontos['y'], c=grupo)
ax.set_aspect('equal', 'box')

ax.scatter(centroides.x, centroides.y, c=[1, 2, 3], marker='+', s=200, cmap='viridis')

for idx, col in pontos.iterrows():
     ax.annotate(idx, (col['x'], col['y'] + .05) )

