# -*- coding: utf-8 -*-
"""realize_a_aplicacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_fZJwZ5Js-WrV34ovLClI28oY3R3rfeA
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

X_train = pd.read_feather('X_train.ftr')
y_train = pd.read_feather('y_train.ftr')
X_test = pd.read_feather('X_test.ftr')
y_test = pd.read_feather('X_test.ftr')
labels = pd.read_feather('/content/activity_labels.ftr')

# Extract categories: combine the column name (first label) with the row values (remaining labels)
all_categories = [labels.columns[0]] + labels.iloc[:, 0].tolist()

# Variável-resposta é o label
y_train_cat = pd.Categorical.from_codes(codes=(y_train-1).values.flatten(), categories=all_categories) # Transformando label em categorical do pandas
y_train_cat.value_counts()

"""## Padronizando as variáveis

Média =  0 e Desvio padrão = 1
"""



# The error indicates that cells in X_train contain strings with multiple space-separated float values.
# We need to parse these strings into individual numerical columns.

# Assuming X_train has a single column (e.g., column 0) that contains these strings.
# Extract the first (and likely only) column as a Series
string_data = X_train.iloc[:, 0]

# Split each string in the Series into a list of float values
# .strip() to remove leading/trailing whitespace, then .split() by spaces
# Convert each part to float
parsed_rows = string_data.apply(lambda x: [float(val) for val in x.strip().split()])

# Convert the list of lists into a new DataFrame with proper numerical columns
X_train_numeric = pd.DataFrame(parsed_rows.tolist())

# Apply StandardScaler to the newly created numerical DataFrame
X_pad = pd.DataFrame(StandardScaler().fit_transform(X_train_numeric), columns = X_train_numeric.columns)

X_pad['y'] = y_train_cat

# Seleção de variáveis através da mediana

med_por_grupo = X_pad.groupby('y').median()
med_por_grupo

colunas = med_por_grupo.abs().idxmax(axis=1).values
colunas

med_por_grupo[colunas]

colunas2 = list(colunas) + ['y']
colunas2

sns.pairplot(X_pad[colunas2], hue='y')

"""## K-Means"""

cluster = KMeans(n_clusters=6)
cluster.fit_predict(X_pad[colunas])

cluster.labels_

X_pad['grupos'] = pd.Categorical(cluster.labels_)
colunas3 = list(colunas) + ['grupos']

sns.pairplot(X_pad[colunas3], hue='grupos')

pd.crosstab(X_pad.y, X_pad.grupos)

def dataviz_grupos(varx):
    fig, ax = plt.subplots(2, 1, sharex=True, figsize=(10, 8))

    sns.boxplot(data=X_pad, y='grupos', x=varx, ax=ax[0])
    sns.boxplot(data=X_pad, y='y', x=varx, ax=ax[1])
    plt.show()

dataviz_grupos(colunas[1])

from scipy.stats import ttest_ind

# Usaremos teste t através da função ttest_ind do scipy.

ttest_ind(X_pad.loc[X_pad.y.cat.codes == 0,colunas[0]], # Comparando as médias desses valores
          X_pad.loc[X_pad.y.cat.codes != 0,colunas[0]]) # com a média desses valores

# Quanto mais diferentes esses valores, maior será a estatística (a nossa deu 54.721789848723944)
# e menor será o pvalue

estatisticas_t = med_por_grupo.copy()
estatisticas_t.loc[:,:] = 0
estatisticas_t

for var in [estatisticas_t.columns]:
    for grupo in X_pad.y.unique():
        estatisticas_t.loc[grupo, var] = ttest_ind(X_pad.loc[X_pad.y == grupo, var],
                                                   X_pad.loc[X_pad.y != grupo, var])[0]

estatisticas_t

colunas_tt = estatisticas_t.abs().idxmax(axis=1).values
colunas_tt

cluster.fit_predict(X_pad[colunas_tt])
X_pad['grupos2'] = pd.Categorical(cluster.labels_)
colunas4 = list(colunas) + ['grupos2']

sns.pairplot(X_pad[colunas4], hue='grupos2')

pd.crosstab(X_pad.y, X_pad.grupos2)

def dataviz_grupos2(varx):
    fig, ax = plt.subplots(2, 1, sharex=True, figsize=(10, 8))

    sns.boxplot(data=X_pad, y='grupos2', x=varx, ax=ax[0])
    sns.boxplot(data=X_pad, y='y', x=varx, ax=ax[1])
    plt.show()

dataviz_grupos2(colunas_tt[3])