# -*- coding: utf-8 -*-
"""sql_m01_tarefa_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1csjk7NaVStjwoBPWDOkvk-Aw3xE49V-p
"""

import pandas as pd

"""## Query 1

"""

query_01 = pd.read_csv('query_01.csv')
query_01

"""## Query 2"""

query_02 = pd.read_csv('query_02.csv')
query_02

"""## Query 3"""

query_03 = pd.read_csv('query_03.csv')
query_03