# -*- coding: utf-8 -*-
"""gere_analises_mensais.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f-mbPXRyoiK8mJyaZDFdy7yWjA-AMOzt

### Carregando a base SINASC de janeiro
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

sns.set()

sinasc = pd.read_csv('SINASC_RO_2019.csv')
sinasc['DTNASC'] = pd.to_datetime(sinasc['DTNASC'], errors='coerce')
df_janeiro = sinasc[sinasc['DTNASC'].dt.month == 1]
df_janeiro.head()

df_janeiro.DTNASC.value_counts().sort_index()

df_janeiro.DTNASC.min(), df_janeiro.DTNASC.max()

"""### Gráficos"""

# Média de Idade da Mãe por Dia do Mês de Janeiro

pd.pivot_table(df_janeiro, values='IDADEMAE', index='DTNASC', aggfunc='mean').plot(figsize=[15, 5])
plt.ylabel('Média de Idade da Mãe')
plt.title('Média de Idade da Mãe por Dia do Mês de Janeiro de 2019')

# Quantidade de bebês ao longo do tempo

pd.pivot_table(df_janeiro, values='IDADEMAE', index='DTNASC', aggfunc='count').plot(figsize=[15, 5])
plt.ylabel('Quantidade de Nascimentos')
plt.title('Quantidade de Bebês ao Longo do Tempo em Janeiro')

# Quantidade de bebês femininos/masculinos por mês

pd.pivot_table(df_janeiro, values='IDADEMAE', index=['DTNASC', 'SEXO'], aggfunc='count').unstack().plot(figsize=[18, 6])
plt.title('Quantidade de Bebês por Mês e Sexo')

# Média de peso dos bebês femiminos/masculinos

pd.pivot_table(df_janeiro, values='PESO', index=['DTNASC', 'SEXO'], aggfunc='count').unstack().plot(figsize=[18, 6])
plt.title('Média de Peso dos Bebês por Mês e Sexo')

# Peso X Escolaridade da Mãe (ESCMAE)

pd.pivot_table(df_janeiro, values='PESO', index='ESCMAE', aggfunc='median').sort_values('PESO').plot(figsize=[18, 6])
plt.ylabel('Peso')
plt.title('Peso X Escolaridade da Mãe')

# Gestação

pd.pivot_table(df_janeiro, values='APGAR1', index='GESTACAO', aggfunc='mean').sort_values('APGAR1').plot(figsize=[18, 6])
plt.ylabel('Média de APGAR1')

pd.pivot_table(df_janeiro, values='APGAR5', index='GESTACAO', aggfunc='mean').sort_values('APGAR5').plot(figsize=[18, 6])
plt.ylabel('Média de APGAR5')

"""### Construir uma função para criar gráficos"""

def analise_sinasc_janeiro_2019(df, value, index, aggfunc):
  pd.pivot_table(df, values=value, index=index, aggfunc=aggfunc).plot(figsize=(18, 6))

  return None

analise_sinasc_janeiro_2019(df_janeiro, 'IDADEMAE', 'DTNASC', 'mean')

def analise_sinasc_janeiro_2019(df, value, index, aggfunc, ylabel, title):
  pd.pivot_table(df, values=value, index=index, aggfunc=aggfunc).plot(figsize=(18, 6))
  plt.ylabel(ylabel)
  plt.title(title)

  return None

analise_sinasc_janeiro_2019(df_janeiro, 'IDADEMAE', 'DTNASC', 'mean',
                            'Média de Idade da Mãe', 'Média de Idade da Mãe por Dia do Mês de Janeiro de 2019')

def analise_sinasc_janeiro_2019(df, value, index, aggfunc, ylabel, xlabel, opcao='nada'):
   if opcao == 'nada':
        pd.pivot_table(df, values=value, index=index, aggfunc=aggfunc).plot(figsize=[15, 5])
   elif opcao == 'sort':
        pd.pivot_table(df, values=value, index=index, aggfunc=aggfunc).sort_values(value).plot(figsize=[15, 5])
   elif opcao == 'unstack':
        pd.pivot_table(df, values=value, index=index, aggfunc=aggfunc).unstack().plot(figsize=[15, 5])

   plt.ylabel(ylabel)
   plt.xlabel(xlabel)

   return None

analise_sinasc_janeiro_2019(df_janeiro, 'APGAR5', 'GESTACAO', 'mean',
                            'APGAR5 Médio', 'Tempo de Gestação', 'sort')

"""### Salvando esses gráficos"""

import os

# Pacote 'os' permite criar um diretório

# Verificando em qual diretório estamos

os.getcwd()

max_data = str(df_janeiro.DTNASC.max())[:7]
max_data

# Criando um diretório para o mês de janeiro de 2019

os.makedirs('/content/output/figs/' + max_data, exist_ok=True)

analise_sinasc_janeiro_2019(df_janeiro, 'IDADEMAE', 'DTNASC', 'mean',
                            'Média de Idade da Mãe', 'Data')
plt.savefig('/content/output/figs/2019-01/' + 'media_idade_mae.png')

analise_sinasc_janeiro_2019(df_janeiro, 'IDADEMAE', 'DTNASC', 'count',
                            'Quantidade de Nascimentos', 'Data')
plt.savefig('/content/output/figs/2019-01/' + 'qtd_nascimentos.png')

analise_sinasc_janeiro_2019(df_janeiro, 'PESO', 'ESCMAE', 'median',
                            'Peso do Bebê', 'Escolaridade da Mãe', 'sort')
plt.savefig('/content/output/figs/2019-01/' + 'escolaridade_mae.png')

analise_sinasc_janeiro_2019(df_janeiro, 'APGAR1', 'GESTACAO', 'mean',
                            'APGAR1', 'Tempo de Gestação', 'sort')
plt.savefig('/content/output/figs/2019-01/' + 'apgar1_tempo_gestacao.png')

analise_sinasc_janeiro_2019(df_janeiro, 'APGAR5', 'GESTACAO', 'mean',
                            'APGAR5', 'Tempo de Gestação', 'sort')
plt.savefig('/content/output/figs/2019-01/' + 'apgar5_tempo_gestacao.png')

analise_sinasc_janeiro_2019(df_janeiro, 'IDADEMAE', ['DTNASC', 'SEXO'], 'mean',
                            'Média Idade Mãe', 'Data', 'unstack')
plt.savefig('/content/output/figs/2019-01/' + 'qtd_nascimentos_sexo.png')

analise_sinasc_janeiro_2019(df_janeiro, 'PESO', ['DTNASC', 'SEXO'], 'count',
                            'Média Idade Mãe', 'Data', 'unstack')
plt.savefig('/content/output/figs/2019-01/' + 'peso_sexo.png')