# -*- coding: utf-8 -*-
"""m14_tarefa_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r2r2pBOpunQkNK3KY0uSmvjt83s_CXc-

## 1. Crie um Jupyter Notebook com os imports necessários e um código para gerar os gráficos referentes a base de dados de março, abril, maio, junho e dezembro (numa célula só ou em várias).

### Março
"""

# Importando as bibliotecas

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

# Função para criar os gráficos

def analise_sinasc_marco_2019(df, value, index, aggfunc, ylabel, xlabel, opcao='nada'):
   if opcao == 'nada':
        pd.pivot_table(df, values=value, index=index, aggfunc=aggfunc).plot(figsize=[15, 5])
   elif opcao == 'sort':
        pd.pivot_table(df, values=value, index=index, aggfunc=aggfunc).sort_values(value).plot(figsize=[15, 5])
   elif opcao == 'unstack':
        pd.pivot_table(df, values=value, index=index, aggfunc=aggfunc).unstack().plot(figsize=[15, 5])

   plt.ylabel(ylabel)
   plt.xlabel(xlabel)

   return None

# Lendo o dataframe

df_marco = pd.read_csv('SINASC_RO_2019_MAR.csv')

# Criando um diretório apenas para o mês de março

max_data = df_marco.DTNASC.max()[:7]
max_data
os.makedirs('/content/output/figs/' + max_data, exist_ok=True)

# Criando os gráficos e salvando-os na pasta criada

analise_sinasc_marco_2019(df_marco, 'IDADEMAE', 'DTNASC', 'mean',
                            'Média de Idade da Mãe', 'Data')
plt.savefig('/content/output/figs/2019-03/' + 'media_idade_mae.png')

analise_sinasc_marco_2019(df_marco, 'IDADEMAE', 'DTNASC', 'count',
                            'Quantidade de Nascimentos', 'Data')
plt.savefig('/content/output/figs/2019-03/' + 'qtd_nascimentos.png')

analise_sinasc_marco_2019(df_marco, 'PESO', 'ESCMAE', 'median',
                            'Peso Mediano', 'Escolaridade da Mãe')
plt.savefig('/content/output/figs/2019-03/' + 'peso_escolaridade_mae.png')

analise_sinasc_marco_2019(df_marco, 'APGAR1', 'GESTACAO', 'mean',
                            'APGAR1', 'Tempo de Gestação', 'sort')
plt.savefig('/content/output/figs/2019-03/' + 'apgar1_tempo_gestacao.png')

analise_sinasc_marco_2019(df_marco, 'APGAR5', 'GESTACAO', 'mean',
                            'APGAR5', 'Tempo de Gestação', 'sort')
plt.savefig('/content/output/figs/2019-03/' + 'apgar5_tempo_gestacao.png')

analise_sinasc_marco_2019(df_marco, 'IDADEMAE', ['DTNASC', 'SEXO'], 'mean',
                            'Média Idade Mãe', 'Data', 'unstack')
plt.savefig('/content/output/figs/2019-03/' + 'qtd_nascimentos_sexo.png')

analise_sinasc_marco_2019(df_marco, 'PESO', ['DTNASC', 'SEXO'], 'count',
                            'Média Idade Mãe', 'Data', 'unstack')
plt.savefig('/content/output/figs/2019-03/' + 'peso_sexo.png')

"""### Abril"""

# Importando as bibliotecas

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

# Função para criar os gráficos

def analise_sinasc_abril_2019(df, value, index, aggfunc, ylabel, xlabel, opcao='nada'):
   if opcao == 'nada':
        pd.pivot_table(df, values=value, index=index, aggfunc=aggfunc).plot(figsize=[15, 5])
   elif opcao == 'sort':
        pd.pivot_table(df, values=value, index=index, aggfunc=aggfunc).sort_values(value).plot(figsize=[15, 5])
   elif opcao == 'unstack':
        pd.pivot_table(df, values=value, index=index, aggfunc=aggfunc).unstack().plot(figsize=[15, 5])

   plt.ylabel(ylabel)
   plt.xlabel(xlabel)

   return None

# Lendo o dataframe

df_abril = pd.read_csv('/content/SINASC_RO_2019_ABR.csv')

# Criando um diretório apenas para o mês de abril

max_data = df_abril.DTNASC.max()[:7]
max_data
os.makedirs('/content/output/figs/' + max_data, exist_ok=True)

# Criando os gráficos e salvando-os na pasta criada

analise_sinasc_abril_2019(df_abril, 'IDADEMAE', 'DTNASC', 'mean',
                            'Média de Idade da Mãe', 'Data')
plt.savefig('/content/output/figs/2019-04/' + 'media_idade_mae.png')

analise_sinasc_abril_2019(df_abril, 'IDADEMAE', 'DTNASC', 'count',
                            'Quantidade de Nascimentos', 'Data')
plt.savefig('/content/output/figs/2019-04/' + 'qtd_nascimentos.png')

analise_sinasc_abril_2019(df_abril, 'PESO', 'ESCMAE', 'median',
                            'Peso Mediano', 'Escolaridade da Mãe')
plt.savefig('/content/output/figs/2019-04/' + 'peso_escolaridade_mae.png')

analise_sinasc_abril_2019(df_abril, 'APGAR1', 'GESTACAO', 'mean',
                            'APGAR1', 'Tempo de Gestação', 'sort')
plt.savefig('/content/output/figs/2019-04/' + 'apgar1_tempo_gestacao.png')

analise_sinasc_abril_2019(df_abril, 'APGAR5', 'GESTACAO', 'mean',
                            'APGAR5', 'Tempo de Gestação', 'sort')
plt.savefig('/content/output/figs/2019-04/' + 'apgar5_tempo_gestacao.png')

analise_sinasc_abril_2019(df_abril, 'IDADEMAE', ['DTNASC', 'SEXO'], 'mean',
                            'Média Idade Mãe', 'Data', 'unstack')
plt.savefig('/content/output/figs/2019-04/' + 'qtd_nascimentos_sexo.png')

analise_sinasc_abril_2019(df_abril, 'PESO', ['DTNASC', 'SEXO'], 'count',
                            'Média Idade Mãe', 'Data', 'unstack')
plt.savefig('/content/output/figs/2019-04/' + 'peso_sexo.png')

"""### Maio"""

# Importando as bibliotecas

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

# Função para criar os gráficos

def analise_sinasc_maio_2019(df, value, index, aggfunc, ylabel, xlabel, opcao='nada'):
   if opcao == 'nada':
        pd.pivot_table(df, values=value, index=index, aggfunc=aggfunc).plot(figsize=[15, 5])
   elif opcao == 'sort':
        pd.pivot_table(df, values=value, index=index, aggfunc=aggfunc).sort_values(value).plot(figsize=[15, 5])
   elif opcao == 'unstack':
        pd.pivot_table(df, values=value, index=index, aggfunc=aggfunc).unstack().plot(figsize=[15, 5])

   plt.ylabel(ylabel)
   plt.xlabel(xlabel)

   return None

# Lendo o dataframe

df_maio = pd.read_csv('/content/SINASC_RO_2019_MAI.csv')

# Criando um diretório apenas para o mês de maio

max_data = df_maio.DTNASC.max()[:7]
max_data
os.makedirs('/content/output/figs/' + max_data, exist_ok=True)

# Criando os gráficos e salvando-os na pasta criada

analise_sinasc_maio_2019(df_maio, 'IDADEMAE', 'DTNASC', 'mean',
                            'Média de Idade da Mãe', 'Data')
plt.savefig('/content/output/figs/2019-05/' + 'media_idade_mae.png')

analise_sinasc_maio_2019(df_maio, 'IDADEMAE', 'DTNASC', 'count',
                            'Quantidade de Nascimentos', 'Data')
plt.savefig('/content/output/figs/2019-05/' + 'qtd_nascimentos.png')

analise_sinasc_maio_2019(df_maio, 'PESO', 'ESCMAE', 'median',
                            'Peso Mediano', 'Escolaridade da Mãe')
plt.savefig('/content/output/figs/2019-05/' + 'peso_escolaridade_mae.png')

analise_sinasc_maio_2019(df_maio, 'APGAR1', 'GESTACAO', 'mean',
                            'APGAR1', 'Tempo de Gestação', 'sort')
plt.savefig('/content/output/figs/2019-05/' + 'apgar1_tempo_gestacao.png')

analise_sinasc_maio_2019(df_maio, 'APGAR5', 'GESTACAO', 'mean',
                            'APGAR5', 'Tempo de Gestação', 'sort')
plt.savefig('/content/output/figs/2019-05/' + 'apgar5_tempo_gestacao.png')

analise_sinasc_maio_2019(df_maio, 'IDADEMAE', ['DTNASC', 'SEXO'], 'mean',
                            'Média Idade Mãe', 'Data', 'unstack')
plt.savefig('/content/output/figs/2019-05/' + 'qtd_nascimentos_sexo.png')

analise_sinasc_maio_2019(df_maio, 'PESO', ['DTNASC', 'SEXO'], 'count',
                            'Média Idade Mãe', 'Data', 'unstack')
plt.savefig('/content/output/figs/2019-05/' + 'peso_sexo.png')

"""### Junho"""

# Importando as bibliotecas

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

# Função para criar os gráficos

def analise_sinasc_junho_2019(df, value, index, aggfunc, ylabel, xlabel, opcao='nada'):
   if opcao == 'nada':
        pd.pivot_table(df, values=value, index=index, aggfunc=aggfunc).plot(figsize=[15, 5])
   elif opcao == 'sort':
        pd.pivot_table(df, values=value, index=index, aggfunc=aggfunc).sort_values(value).plot(figsize=[15, 5])
   elif opcao == 'unstack':
        pd.pivot_table(df, values=value, index=index, aggfunc=aggfunc).unstack().plot(figsize=[15, 5])

   plt.ylabel(ylabel)
   plt.xlabel(xlabel)

   return None

# Lendo o dataframe

df_junho = pd.read_csv('/content/SINASC_RO_2019_JUN.csv')

# Criando um diretório apenas para o mês de junho

max_data = df_junho.DTNASC.max()[:7]
max_data
os.makedirs('/content/output/figs/' + max_data, exist_ok=True)

# Criando os gráficos e salvando-os na pasta criada

analise_sinasc_junho_2019(df_junho, 'IDADEMAE', 'DTNASC', 'mean',
                            'Média de Idade da Mãe', 'Data')
plt.savefig('/content/output/figs/2019-06/' + 'media_idade_mae.png')

analise_sinasc_junho_2019(df_junho, 'IDADEMAE', 'DTNASC', 'count',
                            'Quantidade de Nascimentos', 'Data')
plt.savefig('/content/output/figs/2019-06/' + 'qtd_nascimentos.png')

analise_sinasc_junho_2019(df_junho, 'PESO', 'ESCMAE', 'median',
                            'Peso Mediano', 'Escolaridade da Mãe')
plt.savefig('/content/output/figs/2019-06/' + 'peso_escolaridade_mae.png')

analise_sinasc_junho_2019(df_junho, 'APGAR1', 'GESTACAO', 'mean',
                            'APGAR1', 'Tempo de Gestação', 'sort')
plt.savefig('/content/output/figs/2019-06/' + 'apgar1_tempo_gestacao.png')

analise_sinasc_junho_2019(df_junho, 'APGAR5', 'GESTACAO', 'mean',
                            'APGAR5', 'Tempo de Gestação', 'sort')
plt.savefig('/content/output/figs/2019-06/' + 'apgar5_tempo_gestacao.png')

analise_sinasc_junho_2019(df_junho, 'IDADEMAE', ['DTNASC', 'SEXO'], 'mean',
                            'Média Idade Mãe', 'Data', 'unstack')
plt.savefig('/content/output/figs/2019-06/' + 'qtd_nascimentos_sexo.png')

analise_sinasc_junho_2019(df_junho, 'PESO', ['DTNASC', 'SEXO'], 'count',
                            'Média Idade Mãe', 'Data', 'unstack')
plt.savefig('/content/output/figs/2019-06/' + 'peso_sexo.png')

"""### Dezembro"""

# Importando as bibliotecas

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

# Função para criar os gráficos

def analise_sinasc_dezembro_2019(df, value, index, aggfunc, ylabel, xlabel, opcao='nada'):
   if opcao == 'nada':
        pd.pivot_table(df, values=value, index=index, aggfunc=aggfunc).plot(figsize=[15, 5])
   elif opcao == 'sort':
        pd.pivot_table(df, values=value, index=index, aggfunc=aggfunc).sort_values(value).plot(figsize=[15, 5])
   elif opcao == 'unstack':
        pd.pivot_table(df, values=value, index=index, aggfunc=aggfunc).unstack().plot(figsize=[15, 5])

   plt.ylabel(ylabel)
   plt.xlabel(xlabel)

   return None

# Lendo o dataframe

df_dezembro = pd.read_csv('/content/SINASC_RO_2019_DEZ.csv')

# Criando um diretório apenas para o mês de dezembro

max_data = str(df_dezembro.DTNASC.max())[:7]
max_data
os.makedirs('/content/output/figs/' + max_data, exist_ok=True)

# Criando os gráficos e salvando-os na pasta criada

analise_sinasc_dezembro_2019(df_dezembro, 'IDADEMAE', 'DTNASC', 'mean',
                            'Média de Idade da Mãe', 'Data')
plt.savefig('/content/output/figs/2019-12/' + 'media_idade_mae.png')

analise_sinasc_dezembro_2019(df_dezembro, 'IDADEMAE', 'DTNASC', 'count',
                            'Quantidade de Nascimentos', 'Data')
plt.savefig('/content/output/figs/2019-12/' + 'qtd_nascimentos.png')

analise_sinasc_dezembro_2019(df_dezembro, 'PESO', 'ESCMAE', 'median',
                            'Peso Mediano', 'Escolaridade da Mãe')
plt.savefig('/content/output/figs/2019-12/' + 'peso_escolaridade_mae.png')

analise_sinasc_dezembro_2019(df_dezembro, 'APGAR1', 'GESTACAO', 'mean',
                            'APGAR1', 'Tempo de Gestação', 'sort')
plt.savefig('/content/output/figs/2019-12/' + 'apgar1_tempo_gestacao.png')

analise_sinasc_dezembro_2019(df_dezembro, 'APGAR5', 'GESTACAO', 'mean',
                            'APGAR5', 'Tempo de Gestação', 'sort')
plt.savefig('/content/output/figs/2019-12/' + 'apgar5_tempo_gestacao.png')

analise_sinasc_dezembro_2019(df_dezembro, 'IDADEMAE', ['DTNASC', 'SEXO'], 'mean',
                            'Média Idade Mãe', 'Data', 'unstack')
plt.savefig('/content/output/figs/2019-12/' + 'qtd_nascimentos_sexo.png')

analise_sinasc_dezembro_2019(df_dezembro, 'PESO', ['DTNASC', 'SEXO'], 'count',
                            'Média Idade Mãe', 'Data', 'unstack')
plt.savefig('/content/output/figs/2019-12/' + 'peso_sexo.png')

"""## 2. Como que você poderia fazer para deixar isso mais automatizado? Descreva na última célula do Notebook o que ajudaria na hora de gerar novos gráficos pros meses/anos seguintes.

No Windows, uma boa opção para automatizar um script é utilizando o Agendador de Tarefas. Outra opção possível é o Selenium. Porém, também existem alguma bibliotecas do Python que permitem fazer isso, como a biblioteca `schedule`.
"""