# -*- coding: utf-8 -*-
"""sql_m03_tarefa_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JtGHjDZbIP3Df_hEvQAqgsUzK1eNG3j6
"""

import pandas as pd

"""## Query 1

"""

query_01 = pd.read_csv('query_1.csv')
query_01

"""## Query 2"""

query_02 = pd.read_csv('query_2.csv')
query_02

"""## Query 3"""

query_03 = pd.read_csv('query_3.csv')
query_03

"""## Query 4"""

query_04 = pd.read_csv('query_4.csv')
query_04

