# -*- coding: utf-8 -*-
"""compreenda_os_elementos_basicos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QzMDLCxEBLNyVpIKBeh87oewK68Bi3hu
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation, PillowWriter
from IPython.display import HTML
import warnings

"""### Funções"""

x = np.linspace(0, 10, 50)
f = lambda x: x**3 - 5 * x ** 2 + 3 * x - 8
y = f(x)

plt.plot(x, y, '-')

"""### Limite"""

x = np.linspace(0, 10, 50)
f = lambda x: 1/x
y = f(x)

plt.plot(x, y, '-')

f(100)

f(1000)

f(1)

f(0.00000001)

# Quando o x tende a 0, o f(x)/y tende ao infinito e vice-versa