# -*- coding: utf-8 -*-
"""explore_aplicacoes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qMdHlxy3p4a-1IZUKNJ-5ihc7XlzoF8y
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf

df = sns.load_dataset('tips')
df['net_bill'] = df['total_bill'] - df['tip']

reg = smf.ols('tip ~ net_bill', data=df).fit()
resumo_reg = reg.summary()
resumo_reg

sns.regplot(y=df['tip'], x=df['net_bill'])

y = df['tip']
x = df['net_bill']

def calcula_sqm(y, y_hat):
  return(((y - y_hat) ** 2).sum())

alpha = 1
beta = 0.09
calcula_sqm(y, alpha + beta * x)

alpha_min = 0.3
alpha_max = 2.3
n_bins = 20
delta1 = (alpha_max - alpha_min) / n_bins
beta_min = 0.045
beta_max = 0.15
delta2 = (beta_max - beta_min) / n_bins

grid_alpha = np.arange(alpha_min, alpha_max, delta1)
grid_beta = np.arange(beta_min, beta_max, delta2)

# Listas vazias que vão receber valores para plotarmos depois
i_alpha = []
i_beta = []
i_eqm = []

for alpha in grid_alpha:
  for beta in grid_beta:
    yhat = alpha + beta * x
    i_alpha.append(alpha)
    i_beta.append(beta)
    i_eqm.append(calcula_sqm(y, yhat))

grid = pd.DataFrame(np.empty((len(grid_alpha) * len(grid_beta), 3)), columns = ['alpha', 'beta', 'eqm'])

grid.alpha = i_alpha
grid.beta = i_beta
grid.eqm = i_eqm

grid

from mpl_toolkits.mplot3d import Axes3D # Eixos 3d
from matplotlib import cm # Color map

fig = plt.figure()
ax = Axes3D(fig)

ax.plot_trisurf(grid.alpha, grid.beta, grid.eqm, cmap=cm.jet, linewidth=0.2)
plt.show()

grid_select = grid[grid.eqm < 360]
fig = plt.figure()
ax = Axes3D(fig)

ax.plot_trisurf(grid_select.alpha, grid_select.beta, grid_select.eqm, cmap=cm.jet, linewidth=0.2)
plt.show()

