# -*- coding: utf-8 -*-
"""m25_tarefa_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nL5r5hx5uGY4DvKhWPnKZkF9XB358iaX

# Cálculo - Tarefa 01

1. Marque quais desses métodos/algoritmos muito populares em ciência de dados são baseados no uso de derivada:

    1. Método Mínimos Quadrados: SIM → a solução clássica da regressão linear é obtida derivando a função de erro quadrático e igualando as derivadas (ou gradiente) a zero. Usa derivadas explicitamente na dedução;
    2. Gradiente descendente: SIM → o método se baseia no gradiente da função de custo, isto é: derivadas parciais em relação aos parâmetros. A direção de atualização vem diretamente das derivadas;
    3. Newton Raphson: SIM → método iterativo baseado em: primeira derivada (gradiente) e segunda derivada (Hessiana). Extremamente dependente de cálculo diferencial;
    4. CART (Árvore de decisão): NÃO → usam critérios de divisão (Gini, entropia, MSE) e avaliam redução de impureza. O processo é combinatorial/discreto. Não envolve derivadas nem gradiente.

2. Dada uma base de dados com uma variável resposta $y$ e um conjunto de variáveis explicativas. Considere uma estrutura de um modelo de regressão. Explique com suas palavras por que não é possível obter parâmetros que forneçam um erro quadrático médio (EQM) menor que o obtido com estimadores de mínimos quadrados.

Não é possível obter parâmetros com EQM menor do que os estimadores de mínimos quadrados orque esses estimadores são, por construção, o ponto global de mínimo da função de erro quadrático médio dentro da classe de modelos considerada.

Dado um modelo de regressão fixo, o erro quadrático médio é uma função dos parâmetros. O método dos mínimos quadrados encontra o valores desses parâmetros que minimizam globalmente essa função. Como se trata de uma função convexa, qualquer outro conjunto de parâmetros produzirá um erro quadrático médio maior ou igual, o que impossibilita obter um EQM menor dentro da mesma estrutura de modelo.
"""