# -*- coding: utf-8 -*-
"""m25_tarefa_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qrw95vbnuL7fQR4ABnTIdL52VnrN4wbd

# Cálculo - Tarefa 02

1 - Calcule de forma numérica a integral da função $x^3$ avaliada entre os pontos $1$ e $2$. Identifique o número de retângulos que você usou.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from matplotlib.animation import FuncAnimation, PillowWriter
from IPython.display import HTML
import warnings

# %matplotlib inline

# Função: é o seno de x
f = lambda x: x**3

def calcula_area(a, b, frame_num, func=f):
    num_bins = frame_num + 1 # Quantidade de retângulos
    delta = (b - a) / num_bins # largura do retângulo
    x_cols = np.linspace(a, b - delta, num_bins) + delta / 2 # Divisão do eixo X
    y_cols = f(x_cols) # alturas dos retângulos

    area = sum(delta * y_cols)
    print(f'Quantidade de retângulos: {num_bins}')
    return area # Retorna apenas o valor numérico

calcula_area(1, 2, 10)

"""2 - Calcule essa área de forma analítica.

Queremos a integral da função f(x) = x³ no intervalo [1, 2]:
$$\int_{1}^{2} x^3 \, dx$$

Primeiro, encontramos a antiderivada. Para isso, usaremos a regra da potência para integração, que que $\int x^n \, dx = \frac{x^{n+1}}{n+1}$:

$$F(x) = \frac{x^{3+1}}{3+1} = \frac{x^4}{4}$$

Em seguida, aplicaremos os limites de integraçao, substituindo o limite superior (2) e subtraindo a substituição do limite inferior (1):
$$\left[ \frac{x^4}{4} \right]_{1}^{2} = F(2) - F(1)$$

Agora, resolvemos tudo isso:
"""

x = 2**4
y = 4
lim_sup = x/y

print(f'Limite superior: {lim_sup}')

a = 1**4
lim_inf = a/y

print(f'Limite inferior: {lim_inf}')

resultado = lim_sup - lim_inf

print(f'Resultado: {resultado}')

"""O nosso resultado anterior foi de 3.746, bem próximo de 3.75."""