# -*- coding: utf-8 -*-
"""m03_tarefa_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xacyX2zlS4DeKBHD-0a1QjI5H3MWinOV

### 01 - Teste de gravidez
Escreva uma célula com controle de fluxos que tem como premissa a existência das seguintes variáveis:

- ```sexo``` como ```str``` indicando os valores '**M**' para masculino e '**F**' para feminino  
- ```beta_hcg``` que indica a quantidade do beta-HCG no sangue em mUI/mL.

A sua tarefa é escrever um código que imprima como resultado "indivíduo do sexo masculino" quando sexo = 'M', caso sexo = 'F', se o valor de beta-HCG for maior que 5, retorne "Positivo" indicando que a paciente está grávida, e retorne "Negativo" caso contrário.

Não mexa nos valores da variável ```sexo``` nem em ```beta_hcg```, e escreva um código que funcione para quaisquer valores possíveis de ambos: ```sexo``` = '**M**' ou '**F**' e ```beta_hcg``` assumindo valores inteiros positivos.
"""

sexo = 'M'
beta_hcg = 0

# seu código vem abaixo desta linha

# fluxo condicional caso o valor do beta_hcg seja maior que 5
if beta_hcg > 5:
    print("Positivo.")
    if sexo == 'M': # fluxo condicional para verificar o gênero do bebê
        print("Indivíduo do sexo masculino.")
    elif sexo == 'F':
        print("Indívudo do sexo feminino.")
    else:
        print("Indivíduo de gênero neutro.")
elif beta_hcg < 5: # fluxo condicional caso o valor do beta_hcg seja menor que 5
    print("Negativo.")
else:
    print("Houve um erro com seu teste de gravidez.") # qualquer outra situação

"""### 02 - Renomeando variáveis

Vamos ver adiante que uma forma de renomear variáveis de um conjunto de dados é através de dicionários - o dicionário deve conter como chave o nome original, associando a cada chave um único valor (tipo *str*) que contenha o nome novo.

A sua tarefa é escrever um dicionário que possa ser utilizado para traduzir as variáveis ```name``` (nome), ```age``` (idade) e ```income``` (renda). Ou seja, esse dicionário deve relacionar as chaves *name, age* e *income* às suas respectivas traduções.
"""

dic_renomeacao = {'name': 'nome',
                  'age': 'idade',
                  'income': 'renda'}
dic_renomeacao

"""### 03 - É divisível?
A sua tarefa é escrever um código que indique se um número ```N``` é divisível por um número P. Escreva um programa que faça essa verificação para quaisquer combinações de ```N``` e ```M``` e devolva uma mensagem indicativa no output.
"""

N = 42
M = 7

#Seu código

# Um número é divisível por outro quando o resto da divisão entre ambos é igual a zero.

if N % M == 0:
    print(f"{N} é divisível por {M}.")
else:
    print(f"{N} não é divisível por {M}.")

"""### 04 - Números primos
> Um número **N** é primo se e somente se é divisível por 1, -1, por **N** e por -**N**.  

Escreva um script que verifica se ```N``` é um número primo, verificando se ```N``` é divisível por todos os números de ```1``` a ```N-1```. Você vai precisar usar alguma ferramenta de *loop* que você aprendeu para isto. No final, devolva uma mensagem no output indicando se o número é primo ou não.
"""

N = 47

# seu código abaixo

# verifica se N é igual a 1 ou -1, pois 1 e -1 são divisíveis por todos os números
if N == 1 or N == -1:
    print(f"{N} não é um número primo.")
else:
    for i in range(2, abs(N)): # a função abs() do Python retorna o valor absoluto de um número
        if N % i == 0:
            print(f"{N} não é um número primo.")
            break
    else:
        print(f"{N} é um número primo.")

"""### 05 - Desafio
O algorítmo do exercício anterior não é o mais eficiente. O que você pode fazer para deixá-lo mais eficiente? Ou seja, executar menos comparações, portanto consumir menos tempo.
1. Será que precisamos correr o loop até o final sempre?
2. Será que precisamos mesmo verificar **todos** os números?
3. Será que precisamos ir até N-1?

Essas perguntas levam ao tipo de pensamento voltado a deixar um algoritmo mais eficiente. Veja se você consegue melhorar o seu.
"""

import math

N = 98

# seu código aqui

# ao verificar se um número é primo, não é necessário percorrer o loop até N-1.
# podemos reduzir o intervalo de busca e verificar apenas até a raiz quadrada de N.

# a explicação para isso é que, se um número tem um divisor maior que a sua raiz quadrada,
# ele também terá um divisor menor do que a raiz quadrada. Assim, não é necessário verificar
# ambos os lados do divisor. Portanto, podemos percorrer apenas até a raiz quadrada de N.

if N == 1 or N == -1:
    print(f"{N} não é um número primo.")
else:
    # Loop para verificar se N é divisível por algum número entre 2 e sqrt(N)
    for i in range(2, int(math.sqrt(abs(N))) + 1):
        if N % i == 0:
            print(f"{N} não é um número primo.")
            break
    else:
        print(f"{N} é um número primo.")

"""### 06 - Peso ideal 1
O IMC (índice de massa corpórea) é um indicador de saúde mais bem aceito que o peso. Ele é calculado como:

$$ IMC = \dfrac{peso}{altura^2}$$

Segundo a OMS, valores *normais* são entre 18.5 e 24.9.

Sua tarefa é encontrar o ponto médio dessa faixa.
"""

# criando variáveis para armzenar os valores dos IMCs

imc_min = 18.5
imc_max = 24.9

imc_ideal = (imc_min + imc_max) / 2
imc_ideal

"""### 07 - Peso ideal 2
Recebendo um valor de altura, encontre o peso '*ideal*' dessa pessoa, que fornece o IMC encontrado acima
"""

altura = 1.70
imc = 21.7 # armazenando o imc numa variável

# Seu código

peso_ideal = imc * altura ** 2 # calculando o peso através do imc e da fórmula fornecida
peso_ideal

"""### 08 - Peso ideal 3
Dada uma lista contendo as alturas de pacientes, crie uma nova lista que contenha o peso '*ideal*' (que fornece o IMC calculado em **Peso ideal 1**) desses pacientes.
"""

lista_alturas = [1.95, 2.05, 1.70, 1.65]

lista_peso_ideal = []

# seu código

# loop para calcular o peso ideal para cada altura na lista
for altura in lista_alturas:
    imc = 21.7
    peso_ideal = imc * altura ** 2
    lista_peso_ideal.append(peso_ideal)

lista_peso_ideal

"""### 09 - Peso ideal 4
Dada uma lista de tuplas - cada elemento da lista é uma tupla contendo altura e peso de um paciente - crie uma nova lista com o IMC desses pacientes.
"""

altura_peso = [(1.80, 90), (1.65, 75), (1.91, 70)]

imc = []

# seu código


# loop para calcular o IMC para cada tupla (altura, peso) na lista
for altura, peso in altura_peso:
    imc_paciente = peso / altura ** 2
    imc.append(imc_paciente)

imc

"""### 10 - Peso ideal 5
Dada uma lista de **listas** - cada elemento da lista é uma **lista** contendo altura e peso de um paciente, adicione mais um elemento à lista de cada paciente contendo o IMC do paciente. Verifique também se é 'baixo', 'normal' ou 'alto' segundo os padrões da OMS em que normal é entre 18.5 e 24.9.

Reflexão: por que no problema anterior temos que criar uma nova lista, e não podemos adicionar os dados de cada indivíduo à tupla?

Em relação à reflexão que foi feita a respeito da tupla: não podemos adicionar os dados de cada indivíduo à tupla, pois as
tuplas são estruturas de dados imutáveis, ou seja, quando tentamos indexar novos elementos a elas, ocorre um erro. Isso é o que ocorreria caso tentassemos adicionar os dados individualmente no exercício anterior.
"""

altura_peso = [[1.80, 90], [1.65, 75], [1.91, 70]]

# seu código

# loop para calcular o IMC e adicionar a classificação para cada lista de paciente
for paciente in altura_peso:
    altura, peso = paciente
    imc = peso / altura**2
    paciente.append(imc)

    if imc < 18.5:
        classificacao = 'baixo'
    elif 18.5 <= imc <= 24.9:
        classificacao = 'normal'
    else:
        classificacao = 'alto'

    paciente.append(classificacao)

altura_peso
