# -*- coding: utf-8 -*-
"""conheça _o_statsmodels_e_patsy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MH-8z9HvxWCRNmNs0FcAGLZtr0kCc8DL
"""

import pandas as pd
import numpy as np
import seaborn as sns
from seaborn import load_dataset
import patsy
import statsmodels.api as sm
import statsmodels.formula.api as smf

tips = sns.load_dataset('tips')
tips['tip_pct'] = tips['tip'] / (tips['total_bill'] - tips['tip'])
tips['net_bill'] = tips['total_bill'] - tips['tip']
tips.head()

"""### Definindo a matriz de modelagem com o patsy"""

y, X = patsy.dmatrices('tip_pct ~ sex + smoker + size + total_bill + 1', tips[:5])

# tip_pct é a variável resposta, que vai ser explicada por sex, smoker, size,
# total_bill, e 1 que é o intercepto (que não precisa ser colocado, só está
# aqui para ser explicitado)

# Esse método desempacota a matriz de design em dois objetos: X e y

X

y

"""### Retirando o intercepto"""

y, X = patsy.dmatrices('tip_pct ~ sex + smoker + size + total_bill + 0', tips[:5])

X

"""### Transformaçõa nos dados com patsy"""

y, X = patsy.dmatrices('tip_pct ~ np.log(size) + standardize(total_bill) + center(tip)', tips[:5])
X

# np.log(size) -> log natural da variável size

# standardize(total_bill) -> é do próprio patsy. Padroniza a variável, nesse caso total_bill.
# Tira a média e divide pelo desvio padrão. Média = 0 e std = 1. É um
# procedimento muito comum.

# center(tip) -> faz a diferença do valor da variável com a média, deixando a variável,
# nesse caso tip, centralizada

y, X = patsy.dmatrices('tip ~ sex + smoker + standardize(size) + center(total_bill) + 0', tips[:5])
X

"""### Somando variáveis"""

y, X = patsy.dmatrices('tip ~ I(size + total_bill) + size + total_bill', tips[:5])
X

"""### Dados categorizados"""

y, X = patsy.dmatrices('tip ~ sex + C(size) + total_bill', tips[:5])
X

"""### Definindo interações"""

y, X = patsy.dmatrices('tip ~ sex + time + sex * time', tips[:5])
X

y, X = patsy.dmatrices('tip ~ sex:time', tips[:5])
X

"""### Aplicando patsy a dados novos"""

novos_dados = tips[20:30]

new_X = patsy.build_design_matrices([X.design_info], novos_dados)
new_X

model = smf.ols('tip ~ sex:time', data=tips).fit()
model.model.data.design_info   # contém o design_info

"""### Usando a API padrão do statsmodels"""

y, X = patsy.dmatrices('tip ~ sex + time + smoker + day', tips)
X

modelo = sm.OLS(y, X).fit()
modelo.summary()

"""### Usando a API formula do statsmodels"""

results = smf.ols('tip_pct ~ sex + size + np.log(total_bill)', tips).fit()
results.summary()