# -*- coding: utf-8 -*-
"""implemente_regressao_multipla.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TW9BPXyHUgwNKCimGjp6efaBjUo1KEpV
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import seaborn as sns
from seaborn import load_dataset
import matplotlib.pyplot as plt
import numpy as np
import patsy
import statsmodels.api as sm
import statsmodels.formula.api as smf

# %matplotlib inline

tips = sns.load_dataset('tips')
tips['tip_pct'] = tips['tip'] / (tips['total_bill'] - tips['tip'])
tips['net_bill'] = tips['total_bill'] - tips['tip']
tips.head()

"""### Regressão Múltipla"""

reg = smf.ols('np.log(tip) ~ sex + day + C(size) + net_bill + smoker', data = tips).fit()
tips['res_log'] = reg.resid
reg.summary()

tips['res_log'] = reg.resid
tips['res_log']

"""### Modificando o modelo"""

reg = smf.ols('np.log(tip) ~ C(size) + net_bill', data = tips).fit()
reg.summary()

tips['res_log'] = reg.resid

"""### Análise de resíduos contra cada uma das variáveis
Estamos em busca de um padrão. Se tivermos resíduos predominante para uma determinada variável, pode sre que a variável deva ficar no modelo.
"""

# Resíduo na escala do log em função do "net_bill", total da conta

sns.scatterplot(x='net_bill', y='res_log', data=tips)
plt.axhline(y=0, color='r', linestyle='--')

# Em função de "sex", gênero do garçom

# A distribuição do resíduo para homem e para mulher está
# bem parecida. Isso significa que ela de fato não é relevante.

sns.boxplot(x='sex', y='res_log', data=tips)

# Em função de "smoker", se a mesa possui algum fumante ou não

sns.boxplot(x='smoker', y='res_log', data=tips)

# Em função de "day", dia da semana

sns.boxplot(x='day', y='res_log', data=tips)

# Em função de "size", quantidade de pessoas na mesa

sns.boxplot(x='size', y='res_log', data=tips)

"""### Análise dos valores preditos"""

# Estamos criando dois plots sobrepostos:
# O primeiro, no x, é o aalor líquido da conta (net_bill)

tips['tip_log'] = np.log(tips['tip'])
tips['pred_log'] = reg.fittedvalues

plt.plot(tips['net_bill'], tips['tip_log'], '.')
plt.plot(tips['net_bill'], tips['pred_log'], 'r.')

# Com base nesse gráfico, vemos uma diferença significativa entre os valores #
# que temos com os valores preditos do modelo. Isso representa a necessidade de
# reajustar o modelo

"""### Reajustando o modelo"""

reg = smf.ols('np.log(tip) ~ C(size) + np.log(net_bill)', data = tips).fit()
reg.summary()

tips['tip_log'] = np.log(tips['tip'])
tips['pred_log'] = reg.fittedvalues

plt.plot(tips['net_bill'], tips['tip_log'], '.')
plt.plot(tips['net_bill'], tips['pred_log'], 'r.')