# -*- coding: utf-8 -*-
"""transforme_a_variavel_resposta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15lGsKqa1PPeq_ttTjNhDhlYkMg-xXI0z
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import seaborn as sns
from seaborn import load_dataset
import matplotlib.pyplot as plt
import numpy as np
import statsmodels.formula.api as smf

# %matplotlib inline

"""### Transformação na variável resposta"""

x = np.arange(0, 1, .001)
df = pd.DataFrame({'y': np.exp(x + np.random.randn(1000) *.08), 'x': x})

sns.regplot(x='x', y='y', data=df)

reg = smf.ols('y ~ x', data=df).fit()
print(reg.summary())
df['res'] = reg.resid

sns.scatterplot(x='x', y='res', data=df, alpha=.75)
plt.axhline(y=0, color='r', linestyle='--')

# Variância aumenta conforme aumentamos o x
# Padrão muito evidente

"""#### Outro jeito de calcular o R²"""

df['pred'] = reg.fittedvalues

r = df[['pred', 'y']].corr().iloc[0, 1]

# Primeiro vamos analisar a correlação entre o valor predito
# e a variável resposta. Lembrando que existe uma relação íntima entre a
# correlação e o R²

np.power(r, 2)

# R-squared: 0.913

"""#### Log da variável resposta usando o Patsy"""

reg = smf.ols('np.log(y) ~ x', data=df).fit()
print(reg.summary())
df['res'] = reg.resid

sns.scatterplot(x='x', y='res', data=df, alpha=.75)
plt.axhline(y=0, color='r', linestyle='--')

# ln(y) = alpha + betaxi + epsiloni

"""#### Não podemos comaprar esse R² (0.936) com o primeiro (0.913). ?????"""

sns.regplot(x='x', y='y', data=df)
plt.plot(df['x'], reg.fittedvalues, 'r,--')

# fittedvalues tá na escala do log e ese último R² está na escala do log. Porém,
# para calcular um R² confiável, precisamos retornar ao y, porque é ele que
# queremos predizer, não o log(y) ou ln(y)

"""#### Portanto, como podemos calcular o R² no y original?"""

df['pred_y'] = np.exp(reg.fittedvalues)

r2 = df[['pred_y', 'y']].corr().iloc[0, 1]

np.power(r2, 2)

sns.regplot(x='x', y='y', data=df)
plt.plot(df['x'], df['pred_y'], 'r,--')