# -*- coding: utf-8 -*-
"""transforme_as_variaveis_preditoras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11M3Qf9ZrFA5MoMcANW7Sj0MFhashLfH_
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import seaborn as sns
from seaborn import load_dataset
import matplotlib.pyplot as plt
import numpy as np
import statsmodels.formula.api as smf

# %matplotlib inline

"""### Padrões nos resíduos"""

# Padrão esperado dos resíduos
df = pd.DataFrame({'y':np.random.randn(200), 'x':np.arange(0,1,.005)})

sns.scatterplot(x = 'x', y = 'y', data = df, alpha = .75)
plt.axhline(y=0, color='r', linestyle='--')

# Padrão côncavo
df['y'] = np.exp(2.5*(df['x']-(df['x'].min()-.1))) + np.random.randn(200)*.1
df['y'] = df['y'] - df['y'].mean()

reg = smf.ols('y ~ x', data = df).fit()
df['res'] = reg.resid

sns.scatterplot(x = 'x', y = 'res', data = df, alpha = .75)
plt.axhline(y=0, color='r', linestyle='--')

sns.regplot(x = 'x', y = 'y', data = df)

# Padrão convexo
df['y'] = np.log((df['x']-(df['x'].min()-.1))) + np.random.randn(200)*.05
df['y'] = df['y'] - df['y'].mean()

reg = smf.ols('y ~ x', data = df).fit()
df['res'] = reg.resid

sns.scatterplot(x = 'x', y = 'res', data = df, alpha = .75)
plt.axhline(y=0, color='r', linestyle='--')

sns.regplot(x = 'x', y = 'y', data = df)
plt.plot(df['x'], reg.fittedvalues, 'r,--')

# Padrão de variância crescente
df['y'] = 5*(df['x']-(df['x'].min()-.1)) + (df['x']-(df['x'].min()-.1))*np.random.randn(200)*1.5

reg = smf.ols('y ~ x', data = df).fit()
df['res'] = reg.resid

sns.scatterplot(x = 'x', y = 'res', data = df, alpha = .75)
plt.axhline(y=0, color='r', linestyle='--')

sns.regplot(x = 'x', y = 'y', data = df)

"""### Transformações em x"""

df['y'] = np.log((df['x']-(df['x'].min()-.1))) + np.random.randn(200)*.05
df['y'] = df['y'] - df['y'].mean()
sns.regplot(x = 'x', y = 'y', data = df)

# A regressão com a variável x "crua" resulta em padrão convexo nos resíduos
reg = smf.ols('y ~ x', data=df).fit()
print(reg.summary())
df['res'] = reg.resid

sns.scatterplot(x='x', y='res', data=df, alpha=.75)
plt.axhline(y=0, color='r', linestyle='--')

"""#### Ajustando um polinômio de segundo grau"""

reg = smf.ols('y ~ x + np.power(x, 2)', data=df).fit()
print(reg.summary())
df['res'] = reg.resid

sns.scatterplot(x='x', y='res', data=df, alpha=.75)
plt.axhline(y=0, color='r', linestyle='--')

# Menos resíduo, porém ainda temos um padrão muito evidente. Isso indica que
# ainda podemos melhorar o modelo

sns.regplot(x='x', y='y', data=df)
plt.plot(df['x'], reg.fittedvalues, 'r,--')

# fittedvalues são as nossas predições, valores ajustados
# Nosso polinômio é a linha vermelha

"""#### Ajustando uma função exponencial"""

reg = smf.ols('y ~ np.exp(x)', data=df).fit()
print(reg.summary())
df['res'] = reg.resid

sns.scatterplot(x='x', y='res', data=df, alpha=.75)
plt.axhline(y=0, color='r', linestyle='--')

sns.regplot(x='x', y='y', data=df)
plt.plot(df['x'], reg.fittedvalues, 'r,--')

"""#### Ajustando uma função logarítmica"""

reg = smf.ols('y ~ np.log(x + .1)', data=df).fit()
print(reg.summary())
df['res'] = reg.resid

sns.scatterplot(x='x', y='res', data=df, alpha=.75)
plt.axhline(y=0, color='r', linestyle='--')

sns.regplot(x='x', y='y', data=df)
plt.plot(df['x'], reg.fittedvalues, 'r,--')