# -*- coding: utf-8 -*-
"""utilize_o_statsmodels_para_regressao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SHS9dv1CFYfpRcYYfmS8YNK1jRz9lrb3
"""

import pandas as pd
import seaborn as sns
from seaborn import load_dataset
import matplotlib.pyplot as plt
import numpy as np
import statsmodels.formula.api as smf # importando a api do pacote 'formula' do
# statsmodels

tips = sns.load_dataset('tips')
tips['tip_pct'] = tips['tip'] / (tips['total_bill'] - tips['tip'])
tips['net_bill'] = tips['total_bill'] - tips['tip']
tips.head()

"""### Análise gráfica
Uma boa análise descritiva é fundamental para termos um modelo estatístico de sucesso.
"""

# Gráfico de dispersão
sns.regplot(y = 'tip', x = 'net_bill', data=tips[tips['tip_pct']<.5])

# Gerando dados para a linha dos 10%
x = np.linspace(0, tips['net_bill'].max(), 100)
y = .1 * x # 10% do valor da conta

# Plotando a liha dos 10%
plt.plot(x, y, '-r', label='Linha dos 10%') # Sempre que usamos o comando plot
# ele é adicionado ao último gráfico que foi criado

# Opções estéticas para explicitar o (0, 0) no gráfico
plt.xlim(left=0)
plt.ylim(bottom=0)

"""### Modelo de regressão"""

reg = smf.ols('tip ~ net_bill', data=tips).fit()
reg.summary()

# O pacote formula permite definir um modelo com essa sintaxe
# 'tip ~ net_bill', que possui uma série de vantagens, como adicionar mais
# variáveis e variáveis dummy

"""### Exploração do objeto reg"""

dados_novos = tips[0:5]
dados_novos

# Predição dos dados novos
reg.predict(dados_novos)

type(reg)

reg.params

