# -*- coding: utf-8 -*-
"""sql_m05_tarefa_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jZTVwOsZasJJ7nzizYFWZ4_lUtiZsu67
"""

import pandas as pd

"""## Query 1

```sql
SELECT * FROM heartattack limit 10;
```
"""

query_01 = pd.read_csv('query_01.csv')
query_01

"""## Query 2

```sql
SELECT COUNT(age) AS QUANTIDADE_LINHAS
FROM heartattack
```
"""

query_02 = pd.read_csv('query_02.csv')
query_02

"""## Query 3

```sql
SELECT COUNT(age) AS QUANTIDADE,
CASE
WHEN output =1 THEN ' more chance of heart attack'
ELSE 'less chance of heart attack'
END AS output
FROM heartattack
GROUP BY output;
```
"""

query_03 = pd.read_csv('query_03.csv')
query_03

"""## Query 4

```sql
SELECT MAX(age), MIN(age), AVG(age), output  
FROM heartattack
GROUP BY output
```
"""

query_04 = pd.read_csv('query_04.csv')
query_04

"""## Query 5

```sql
SELECT MAX(age), MIN(age), AVG(age), output ,sex
FROM heartattack
GROUP BY output, sex;
```
"""

query_05 = pd.read_csv('query_05.csv')
query_05

"""## Query 6

```sql
SELECT COUNT(output), output, sex
FROM heartattack
GROUP BY output, sex
having COUNT(output) > 25
```
"""

query_06 = pd.read_csv('query_06.csv')
query_06