# -*- coding: utf-8 -*-
"""analise_variaveis_bivariadas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G5PiUFUwbTexKIV0DjuKnI031ndiz0hX
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

# Fixing random state for reproductability
np.random.seed(2360873)
N = 100

tips = sns.load_dataset("tips")
tips['tip_pct'] = tips['tip'] / tips['total_bill']
tips.head()

ax = sns.pointplot(x='sex', y='tip_pct', data=tips, dodge=True, errorbar=('ci', 90))

ax = sns.pointplot(x='day', y='tip_pct', data=tips, hue='sex', dodge=True, errorbar=('ci', 90))
plt.legend(loc='lower center', bbox_to_anchor=(0.5, -.30), ncol=3)