# -*- coding: utf-8 -*-
"""compreenda_a_estabilidade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A6dpQNHizVSv61-QyIeLktQ4rvkAwbu_
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Fixing random state for reproductability
np.random.seed(2360873)

tips = sns.load_dataset('tips')
tips['tip_pct'] = tips['tip'] / (tips['total_bill'] - tips['tip'])
tips.head()

tips.shape

# Vamos fazer uma reamostragem da base de gorjetas para simular que essa base
# tenha medidas em três meses distintos, para podermos comparar as distribuições
# das variáveis no tempo

n_meses = 3
n_clientes = 210

datas = pd.Series(pd.date_range('1/1/2019', periods=n_meses, freq='MS'). repeat(n_clientes))
dados = tips.sample(n = n_meses * n_clientes, replace=True).reset_index()

tips2 = pd.concat([datas, dados], axis = 1)
tips2.rename({0:'data_ref'}, inplace = True, axis = 'columns')
tips2

"""### Distribuição da variável"""

ax = sns.countplot(x='data_ref', hue='sex', data=tips2)
tick_labs = tips2['data_ref'].map(lambda ts: ts.strftime('%Y-%m')).unique()

# tick_labs.tolist()

ticks = ax.set_xticks(list(range(tips2['data_ref'].nunique())))
labels = ax.set_xticklabels(tick_labs, rotation=90)

plt.legend(bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)

tab = pd.crosstab(tips2['data_ref'],tips2['sex'])
tab.div(tab.sum(axis = 1), axis = 0) # Tabela de frequência com os totais por linhas

tab_freq = pd.crosstab(tips2['data_ref'],tips2['sex'])
tab = tab_freq.div(tab.sum(axis = 1), axis = 0)

ax = tab.plot.bar(stacked = True)

tick_labs = tips2['data_ref'].map(lambda ts: ts.strftime("%m-%Y")).unique()
ticks = ax.set_xticks(list(range(tips2['data_ref'].nunique())))
labels = ax.set_xticklabels(tick_labs, rotation=0)

plt.legend(loc = 'lower center', bbox_to_anchor=(0.5, -.50),ncol = 3)

"""###Perfis médios no tempo"""

# Avaliando o percentual médio de gorjetas tanto para o sexo masc quanto fem
# no tempo e verificando se isso se altera de maneira significativa com o tempo

ax = sns.pointplot(x="data_ref", y="tip_pct", hue = 'sex',
                   data=tips2, dodge=True, errorbar=('ci', 95))

plt.legend(loc = 'lower center', bbox_to_anchor=(0.5, -.30),ncol = 3)

tick_labs = tips2['data_ref'].map(lambda ts: ts.strftime("%m-%Y")).unique()

ticks = ax.set_xticks(list(range(tips2['data_ref'].nunique())))
labels = ax.set_xticklabels(tick_labs, rotation=0)

plt.legend(loc = 'lower center', bbox_to_anchor=(0.5, -.50),ncol = 3)