# -*- coding: utf-8 -*-
"""m10_tarefa_01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RlzZM8MpAn0gHEUhSB7pTqyYnHg6LbqA

Uma instituição financeira quer conhecer melhor o perfil de renda de seus novos clientes para diversos fins, por exemplo, melhor dimensionar o limite de cartões de crédito dos novos clientes, sem necessariamente solicitar olerites ou documentações que impactem na experiência do seu cliente.

Para isto, conduziu um estudo com alguns clientes, comprovando suas rendas através de olerites e outros documentos, e pretende construir um modelo preditivo para esta renda com base em algumas variáveis que já possui em seu banco de dados.

As variáveis são intuitivas - note que há uma variável 'index' que é um identificador do cliente e que em geral o ```read_csv``` do pandas coloca também uma variável sequencial.

Estes dados estão no arquivo ```previsao_de_renda.csv```. Carregue-o em um *dataframe*.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/previsao_de_renda.csv")
df_num = df.select_dtypes(include=['float64', 'int64']).drop(columns=['Unnamed: 0', 'index', 'mau'], errors='ignore')

df_num.head()

# Variáveis a serem ignoradas: mau, index e unnamed

"""1) Avalie a estrutura de correlação das variáveis quantitativas através de um gráfico de "matriz de dispersão" e através da avaliação gráfica da matriz de correlações. Veja se você identifica algum padrão interessante ou que te faça sentido."""

corr = df_num.corr()
corr

sns.pairplot(df_num)
plt.suptitle('Matriz de Dispersão das Variáveis Quantitativas')
plt.show()

plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap='viridis', fmt='.2f', linewidths=0.5)
plt.title('Matriz de Correlação das Variáveis Numéricas', pad=15)
plt.show()

# qt_pessoas_residencia e qtd_filhos também apresentam correlação positiva
# natural. Pois, quanto mais filhos alguém tiver, mais pessoas provavelmente
# morarão na casa dela.

# idade e tempo_emprego estão tendem a ter correlação positiva moderada (quanto
# mais idade, mais tempo de trabalho).

# renda costuma ter correlação com tempo_emprego e idade

"""2) Avalie um gráfico de dispersão (*scatterplot*) específico para as duas variáveis mais correlacionadas com *renda*."""

corr_renda = corr['renda'].drop('renda').sort_values(ascending=False)
corr_renda

# Podemos ver, através dessa matriz, que as duas variáveis com
# maior correlação com a variável renda são tempo_emprego e idade

top2 = corr_renda.head(2).index.tolist()

plt.figure(figsize=(12, 5))

for i, var in enumerate(top2):
    plt.subplot(1, 2, i+1)
    sns.scatterplot(data=df, x=var, y='renda', alpha=0.6)
    plt.title(f'Dispersão: renda vs {var}\nCorrelação: {corr_renda[var]:.2f}')
    plt.xlabel(var)
    plt.ylabel('renda')

plt.show()

"""3) Na sua opinião, há outliers na variável renda?"""

df_num[['renda', 'tempo_emprego']].sort_values(by='renda', ascending=False).head(10)

df_num[['renda', 'idade']].sort_values(by='renda', ascending=False).head(10)

df_num[['renda', 'tempo_emprego', 'idade']].agg(['mean', 'max', 'std'])

"""Definitivamente.

Por exemplo: A pessoa do índice 9934, possui uma renda de 89918.04, 42 anos de tempo de emprego e 62 anos de idade. Tal renda faz sentido, considerando-se tanto tempo de emprego e idade mais avançada.

Porém, o que mais chama atenção é a pessoa do índice 113, que ganha uma renda de 67794.54	com apenas 3 anos no emprego e 25 anos de idade.

Sendo que a média para esses valores é:

- renda: 4624.63
- tempo_emprego: 7.75
- idade: 43

4) Calcule o logaritmo da variável renda e repita a sequência de análise
"""

df['log_renda'] = np.log(df['renda'])
df[['renda', 'log_renda']].head()

df_num_log = df.select_dtypes(include=['float64', 'int64']).drop(columns=['Unnamed: 0', 'index', 'mau', 'renda'], errors='ignore')
corr_log = df_num_log.corr()

plt.figure(figsize=(8,6))
sns.heatmap(corr_log, annot=True, cmap='viridis', fmt='.2f', linewidths=0.5)
plt.title('Matriz de Correlação com log (renda)', pad=15)
plt.show()

corr_log_renda = corr_log['log_renda'].drop('log_renda').sort_values(ascending=False)
corr_log_renda.head(2)

top2_log = corr_log_renda.head(2).index.tolist()

# Criar scatterplots
plt.figure(figsize=(12, 5))

for i, var in enumerate(top2_log):
    plt.subplot(1, 2, i+1)
    sns.scatterplot(data=df, x=var, y='log_renda', alpha=0.6)
    plt.title(f'Dispersão: log(renda) vs {var}\nCorrelação: {corr_log_renda[var]:.2f}')
    plt.xlabel(var)
    plt.ylabel('log(renda)')

plt.tight_layout()
plt.show()

"""5) A aplicação do LOG você acha que melhorou ou piorou a análise?

É possível ver que a distribuição da renda ficou muito mais simétrica e está sendo menos impactada pelos outliers.
"""