# -*- coding: utf-8 -*-
"""m10_tarefa_02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H5_EwdxqkTA_uD4V-Bfk_1h8SiBCz_2-

# Módulo 10 tarefa 2

Considere a mesma base de dados utilizada na tarefa 1 ```previsao_de_renda.csv```.

1) Com o que você viu em aula, faça uma análise das variáveis qualitativas (posse de imóvel e posse de veículo) para verificar se são boas preditoras de *renda*. Alguma delas parece discriminar *renda* de forma estatisticamente significante?
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv("/content/previsao_de_renda.csv")

df['log_renda'] = np.log(df['renda'])

fig, ax = plt.subplots(1, 2, figsize=(12, 5))

# Posse de veículo
sns.pointplot(data=df, x='posse_de_veiculo', y='renda', errorbar=('ci', 95), ax=ax[0])
ax[0].set_title('Intervalos de confiança - Posse de Veículo')
ax[0].set_ylabel('Renda média')

# Posse de imóvel
sns.pointplot(data=df, x='posse_de_imovel', y='renda', errorbar=('ci', 95), ax=ax[1])
ax[1].set_title('Intervalos de confiança - Posse de Imóvel')
ax[1].set_ylabel('Renda média')

plt.tight_layout()
plt.show()

"""É possível ver que os intervalos entre renda e posse de imóvel se sobrepõem, enquanto os intervalos entre renda e posse de veículo não.

Na prática, isso significa que posse de imóvel não é uma variável que funciona bem como preditora de renda, mas de veículo, sim. Se pensarmos a respeito da realidade brasileira, por exemplo, diversos fatores explicam isso:

- Herança ou doação: muita gente possui imóvel porque herdou dos pais ou avós, mesmo tendo renda baixa no presente.
- Programas habitacionais (ex: Minha Casa Minha Vida): muitas famílias de baixa renda conseguiram adquirir imóveis subsidiados.
- Imóveis em áreas baratas: há quem tenha casa própria em regiões periféricas, mas baixa renda mensal.
-----------------------------------------------------
- Carros exigem custos contínuos muito mais frequentes com os quais boa parte da população não pode (ou prefere não) arcar: combustível, IPVA, seguro, manutenção, tudo isso exige renda mensal estável e relativamente alta.
- Crédito e financiamento: quem tem veículo normalmente teve acesso a financiamento bancário, o que já exige renda comprovada.
- Sinal de consumo e mobilidade: o carro é um bem de consumo de classe média, associado à autonomia e poder aquisitivo recente.
"""