# -*- coding: utf-8 -*-
"""mod10_tarefa_03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zmmduWvGC69uIqSvND0D3_E5iW6BS-12

# Módulo 10 tarefa 03
Considere a mesma base de dados utilizada na tarefa 1 ```previsao_de_renda.csv```.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""1) Construa um gráfico de barras para avaliar a distribuição das variáveis quantitativas no tempo. Você acha que houve alguma alteração importante a ser investigada?"""

df = pd.read_csv("/content/previsao_de_renda.csv")
df = df.drop(columns=['Unnamed: 0', 'index'])

df['data_ref'] = pd.to_datetime(df['data_ref'])

plt.figure(figsize=(10, 5))
sns.countplot(data=df, x='data_ref', color='skyblue')

plt.title('Distribuição de registros ao longo do tempo', fontsize=14)
plt.xlabel('Data de referência')
plt.ylabel('Número de observações')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""Com base no gráfico, não é possível ver nenhuma grande alteração ao longo do tempo.
- A variável data_ref não interfere diretamente nas análises de renda;
- Há a mesma quantidade de registros em cada período;
- Não houveram grandes mudanças na população estudada, provavelmente;
- Nenhum mês teve coleta maior ou menor de dados;
- Não há mudanças temporais relevantes para investigar.

Portanto, a base é temporalmente balanceada, sugerindo que o tempo é apenas uma variável de referência e não um fator explicativo.

2) Para cada variável qualitativa, construa um gráfico mostrando as médias de cada nível da variável no tempo e avalie a estabilidade. Houve alguma alteração importante? Você acha que se pode utilizar essas variáveis em uma modelagem?
"""

variaveis_qualitativas = [
    'sexo', 'posse_de_veiculo', 'posse_de_imovel',
    'tipo_renda', 'educacao', 'estado_civil', 'tipo_residencia'
]

for var in variaveis_qualitativas:
    plt.figure(figsize=(10, 5))
    sns.lineplot(data=df, x='data_ref', y='renda', hue=var, errorbar=None, marker='o')
    plt.title(f'Evolução da renda média por {var}')
    plt.xlabel('Data de referência')
    plt.ylabel('Renda média')
    plt.legend(title=var, bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.tight_layout()
    plt.show()

"""###Sexo

Renda média masculina ligeiramente maior que feminina,
mas estável ao longo do tempo → variável estável.

### Posse de veículo/imóvel

- Quem tem veículo → renda média mais alta.

- Diferença constante ao longo do tempo → estáveis.

- **Ótimas para modelagem.**

### Tipo de renda

- Diferenças claras: Empresário > Assalariado > Pensionista etc.
- Linhas paralelas e estáveis → muito boa variável preditora.

### Educação

- Quanto maior o nível educacional, maior a renda média.

- Relação linear e estável → excelente preditora.

### Estado civil

- Diferenças pequenas entre grupos, geralmente estáveis.

- Pode contribuir pouco na modelagem.

### Tipo de residência

Leve variação, mas geralmente estável → pode entrar como variável categórica sem problema.

### Conclusão

As variáveis qualitativas apresentam padrões consistentes e estáveis ao longo do tempo, sem grandes flutuações na renda média entre os meses.

Isso indica que não há evidência de instabilidade temporal que inviabilize o uso dessas variáveis na modelagem.

Assim, variáveis como tipo de renda, educação e posse de veículo se destacam como fortes candidatas preditoras de renda, pois possuem clara discriminação entre categorias e comportamento estável.
"""