# -*- coding: utf-8 -*-
"""m04_tarefa_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Txk2WijmqNmeBzjwQG0ViLtQ4LFwmwx

# Tarefa 01

- Leia os enunciados com atenção
- Saiba que pode haver mais de uma resposta correta
- Insira novas células de código sempre que achar necessário
- Em caso de dúvidas, procure os tutores
- Divirta-se :)

#### 1)  Crie uma série do pandas a partir de uma lista com os dados abaixo:

Em um estudo sobre alteração na tempreatura global, A NASA disponibiliza dados de diferenças de temperatura média da superfície terrestre relativos às médias de temperatura entre 1951 e 1980. Os dados originais podem ser vistos no site da NASA/GISS, e estão dispostos a cada década na tabela abaixo.

|ano|anomalia termica|
|:-:|:----:|
| 1900 | -0.08 |
| 1920 | -0.27 |
| 1940 | 0.12 |
| 1960 | -0.03 |
| 1980 | 0.26 |
| 2000 | 0.40 |
| 2020 | 1.02 |

Crie uma séries do Pandas a partir de uma lista com esses dados.
"""

import pandas as pd
import numpy as np

# Seu código aqui

# criando uma lista com os valores da coluna de anomalias térmicas e armazenando
# numa variável chamada temperaturas

temperaturas = [-0.08, -0.27, 0.12, -0.03, 0.26, 0.40, 1.02]

# criando uma série do pandas a partir da lista de temperaturas

anomalias_termicas = pd.Series(data=temperaturas)

# imprimindo a série

anomalias_termicas

"""#### 2) Coloque os anos nos índices conforme a tabela."""

# seu código aqui

# criando uma lista com todos os anos listados na primeira coluna

anos = [1900, 1920, 1940, 1960, 1980, 2000, 2020]

# criando uma série do pandas utilizando a lista de temperaturas criada na
# célula acima como os dados e a lista de anos como índices

anomalias_termicas = pd.Series(data=temperaturas, index=anos)

# imprimindo a série

anomalias_termicas

"""#### 3) A partir do dicionário abaixo, crie uma séries do Pandas:"""

dic_temperaturas = {1900: -.08, 1920: -.27, 1940: .12, 1960: -.03, 1980: .26, 2000: .40, 2020: 1.02}

# seu código aqui

# criando uma série do pandas a partir de um dicionário, onde as chaves são os
# índices e os valores são os dados

anomalias_termicas = pd.Series(data=dic_temperaturas)

# imprimindo a série

anomalias_termicas

"""#### 4) Transforme o ndarray abaixo em um dataframe.
O numpy é capaz de gerar arrays n-dimensionais com números pseudo-aleatórios de acordo com uma variedade de distribuições, como no exemplo abaixo. Transforme esse nd-array em um DataFrame.
"""

arr = np.random.normal(100, 10, (20,3))

# seu código aqui

# criando um dataframe do pandas a partir do ndarray acima e armazenando-o na
# variável df

df = pd.DataFrame(arr)

# imprimindo o dataframe

df

"""#### 5) Nomeie os índices das linhas com inteiros de 1 a 20, e as colunas com os nomes "x1", "x2", e "x3" respectivamente."""

#seu código aqui

# abaixo, estou definindo o dataFrame df. Para os valores, passei o ndarray arr
# para nomear as colunas utilizei a função map, passando um lambda que irá
# concatenar 'x' e os números das colunas. Em seguida também passei para a
# função map uma lista com os números das colunsa, em string, para concatenar.
# Para nomear as linhas, passei um range que começa em 1 e termina em 21
# (pois a função range sempre exclui o segundo número passado ao fazer a
# iteração)

df = pd.DataFrame(arr,
                  columns=map(lambda valor: 'x' + valor, ['1', '2', '3']),
                  index=range(1, 21))

df

"""#### 6) No DataFrame do exercício 5, crie uma nova coluna como sendo a média das três colunas, e dê a ela o nome de "media" (não recomendo colocar acentos em nomes de variáveis)."""

# seu código aqui

# para realizar o cálculo da média, utilizei o método dataframe.mean() do pandas
# que realiza o cálculo de uma média, passando o parâmetro axis = 1, indicando
# que a média deve ser calculada ao longo das colunas

df['media'] = df.mean(axis=1)

# imprimindo o dataFrame

df

"""#### 7) No DataFrame do exercício 6, crie uma nova coluna chamada "log_med", contendo o logaritmo natural da média calculada no exercício 6 <br>"""

# seu código aqui

# numpy.log () é uma função matemática que ajuda o usuário a calcular o
# logaritmo natural de x, onde x pertence a todos os elementos da matriz de
# entrada. Log do logaritmo natural é o inverso de exp (), de modo que log
# (exp (x)) = x. O logaritmo natural é logarítmico na base e.

# utilizei o método numpy.log(), que realiza o cálculo do logaritmo natural,
# passando como parâmetro a coluna media. Em seguida atribui o resultado
# como coluna ao dataframe

df['log_med'] = np.log(df['media'])

# imprmindo o dataframe

df