# -*- coding: utf-8 -*-
"""compreenda_o_markdown_no_jupyter_notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u3x6kG2ZCela5igLbCBXUjcwnvrL9cXB

### Citação

- Citação usando >

**Harper Lee**:

>"Coragem é fazer algo mesmo sabendo que você está derrotado antes de começar, e ir até o fim, apesar de tudo, porque a verdadeira bravura não está na vitória, mas na perseverança e na integridade moral diante do inevitável, mesmo que você raramente vença."

- Citação usando `<blockquote>`

**Muriel Barbery**
<blockquote>"Mas tudo veio em sua hora... Tudo vem na hora certa pra quem sabe esperar..."</blockquote>

### Código
- Usando `

`x = 5`

- Usando ```

```Python
# Isso é um comentário no trecho
frase = "Python"
print(frase)
```

```C
int V[10];
V[1] = 35;
V[2] = 11;
```

### Quebra de linhas
É possível fazer isso através da tag `<br>`.

Isso é um trecho <br> de texto.

### Link de seções
`<a id="division_ID"></a>`
<a id="division_ID"></a>

### Lista com números
1. Um
2. Dois
3. Três

### Lista não ordenada
- Um
- Dois
- Três

[Divisão](#division_ID)

### Link externo
`<a href="link">Título</a>` <br>
<a href="https://link.springer.com/article/10.1007/s00500-022-06734-4">A comprehensive overview of AI-enabled music classification and its influence in games</a> <br>
<br>
`[Título](Link)`

[How Music Resonates in the Brain](https://magazine.hms.harvard.edu/articles/how-music-resonates-brain)

### Imagem
`<img src="url" width="250" height="20">` <br>
<img src="https://i.pinimg.com/1200x/aa/01/f1/aa01f12541dc08fa36893a1db4cb8700.jpg" width="500" height="350">
<br>
<br>
`![Título](caminho)`
<br>
![The Anatomy Lesson of Dr. Nicolaes Tulp](/content/Rembrandt_-_The_Anatomy_Lesson_of_Dr_Nicolaes_Tulp.jpg)
"""