# -*- coding: utf-8 -*-
"""compreenda_o_latex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K_k-duRq8aFBQoFgrXqWqKkM-BBNDgbo

## Sintaxe
### Fórmula simples
`$x^2$`
<br><br>
$x^2$

Qualquer número ao quadrado: $x^2$

### Fórmula centralizada

`$$x^2$$`
$$x^2$$

Qualquer número ao quadrado: $$x^2$$

### Quebra de linha

$$x^2\\
x^3$$

### Fração
`$\frac{num}{dem}$`<br><br>

$\frac{4}{2}$

### Raiz quadrada
`$\sqrt{x}$` <br><br>
$\sqrt{100}$
<br><br><br>

`$\sqrt[3]{x}$` <br><br>
$\sqrt[3]{100}$

### Exponencial
`$e^{x}$` <br><br>
$e^{100}$

### Exemplo de fórmula
$$e^{\frac{2}{4}}$$

### Sobrescrito
`$i^n$`<br><br>
$i^n$
<br><br><br>
`$^ni$`<br><br>
$^ni$

### Subscrito
`$i_n$` <br><br>
$n_i$
<br><br><br>
`$n_{ij}$`<br><br>$n_{ij}$

### Letras gregas
- Pi: `$\pi$`<br>
$\pi$
- Alpha: `$\alpha$` <br> $\alpha$
- Beta: `$\beta$` <br> $\beta$
- Omega: `$\omega$` <br> $\omega$
- Lambda: `$\lambda$` <br> $\lambda$

### Limites
- Tendendo a + infinito: `$\lim_{x \to +\infty} f(x)$` <br> $\lim_{x \to \infty} f(x)$

- Tendendo a - infinito: `$\lim_{x \to -\infty} f(x)$` <br> $\lim_{x \to -\infty} f(x)$

- Tendendo a alpha: `$\lim_{x \to \alpha} f(x)$` <br> $\lim_{x \to \alpha} f(x)$
"""