# -*- coding: utf-8 -*-
"""M20_tarefa_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GxDK7jEokBEeakGNKA5PSUD5QMZGme37

#### Fórmula de Bhaskara
A solução para uma função de segundo grau depende das suas raízes (valores de x). Como já vimos, os coeficientes precisam ser números reais e o angular diferente de zero. Sendo assim, temos a seguinte fórmula de Bhaskara:
<br><br>
$$x=\frac{-b^ ± \sqrt{b^2 - 4.a.c}}{2.a}   $$
<center><i>Fórmula de Bhaskara</i></center>
<br>
Para melhor compreensão, o seu cálculo é dividido em duas partes: discriminante da equação e operações para determinar as raízes.
<br>
<br>

**Discriminante**<br><br>
A figura dentro da raiz na fórmula de Bhaskara é nomeada de discriminante. Seu símbolo é a letra grega delta e apresenta a determinada fórmula:

$$Δ = b^2 - 4.a.c $$
<center><i>Fórmula da discriminante</i></center>
<br>

- Se o delta for maior que zero, a equação terá dois valores reais e distintos.
- Se o delta for igual a zero, a equação terá somente um valor real ou dois resultados iguais.
- Se o delta for menor que zero, a equação não possuirá valores reais.
"""