# -*- coding: utf-8 -*-
"""diferencie_qualidade_de_complexidade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DoF3SLfUSM9RFKWBhz2ZyXm0vo8dY2yf
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
import statsmodels.api as sm
import patsy
from patsy import dmatrix

# from sklearn.model_selection import train_test_split
# from sklearn import metrics
# from sklearn.ensemble import RandomForestClassifier
# from scipy.stats import ks_2samp

# %matplotlib inline

tips = sns.load_dataset('tips')
tips['tip_pct'] = tips['tip'] / (tips['total_bill'] - tips['tip'])
tips['net_bill'] = tips['total_bill'] - tips['tip']
tips.head()

reg = smf.ols('tip ~ C(size, Treatment(2)) + np.log(net_bill)', data=tips).fit()
reg.summary()

reg = smf.ols('tip ~ C(size, Treatment(2)) + np.log(net_bill) + day', data=tips).fit()
reg.summary()