# -*- coding: utf-8 -*-
"""domine_variaveis_qualitativas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gP-hUbF3mYTMZt2qje9rdIKPukruxjbt
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
import statsmodels.api as sm
import patsy
from patsy import dmatrix

# from sklearn.model_selection import train_test_split
# from sklearn import metrics
# from sklearn.ensemble import RandomForestClassifier
# from scipy.stats import ks_2samp

# %matplotlib inline

tips = sns.load_dataset('tips')
tips['tip_pct'] = tips['tip'] / (tips['total_bill'] - tips['tip'])
tips['net_bill'] = tips['total_bill'] - tips['tip']
tips.head()

sns.pointplot(y='tip', x='size', data=tips)

# Valor da gorjeta em função do tamanho da mesa
# Qua

y, X = patsy.dmatrices('tip ~ C(size)', data=tips)
X

"""### Casela de referência"""

data = pd.DataFrame({'size': [1, 2, 3, 4, 5]})
data

dmatrix('C(size)', data)

sm.OLS(y, X).fit().summary()

1.4375 + 1.1448

# É exatamente o valor de beta2 (beta para mesas de tamanho 2).

y, X = patsy.dmatrices('tip ~ C(size, Treatment(2))', data=tips)
X

sm.OLS(y, X).fit().summary()

-1.1448 + 2.5823

# É o exato valor de beta1 (beta para mesas de tamanho 1)

2.5823 + 0.8109

# É o exato valor de beta3

y, X = patsy.dmatrices('tip ~ C(size, Treatment(3))', data=tips)
sm.OLS(y, X).fit().summary()