# -*- coding: utf-8 -*-
"""m13_tarefa_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NZuwJfCaFDYQ2koXz1tF_4NF6W24FoDI

# EBAC - Regressão II - regressão múltipla

## Tarefa I

#### Previsão de renda

Vamos trabalhar com a base 'previsao_de_renda.csv', que é a base do seu próximo projeto. Vamos usar os recursos que vimos até aqui nesta base.

|variavel|descrição|
|-|-|
|data_ref                | Data de referência de coleta das variáveis |
|index                   | Código de identificação do cliente|
|sexo                    | Sexo do cliente|
|posse_de_veiculo        | Indica se o cliente possui veículo|
|posse_de_imovel         | Indica se o cliente possui imóvel|
|qtd_filhos              | Quantidade de filhos do cliente|
|tipo_renda              | Tipo de renda do cliente|
|educacao                | Grau de instrução do cliente|
|estado_civil            | Estado civil do cliente|
|tipo_residencia         | Tipo de residência do cliente (própria, alugada etc)|
|idade                   | Idade do cliente|
|tempo_emprego           | Tempo no emprego atual|
|qt_pessoas_residencia   | Quantidade de pessoas que moram na residência|
|renda                   | Renda em reais|
"""

import pandas as pd
import pandas as pd
import numpy as np
import patsy
import statsmodels.api as sm
import statsmodels.formula.api as smf

df = pd.read_csv('previsao_de_renda.csv')
df.info()

"""1. Ajuste um modelo para prever log(renda) considerando todas as covariáveis disponíveis.
    - Utilizando os recursos do Patsy, coloque as variáveis qualitativas como *dummies*.
    - Mantenha sempre a categoria mais frequente como casela de referência
    - Avalie os parâmetros e veja se parecem fazer sentido prático.
"""

cats = ['sexo', 'posse_de_veiculo', 'posse_de_imovel',
        'tipo_renda', 'educacao', 'estado_civil', 'tipo_residencia']

for c in cats:
    print(c, "→ referência =", df[c].value_counts().idxmax())

formula = """
np.log(renda) ~
C(sexo, Treatment('F')) +
C(posse_de_veiculo, Treatment(False)) +
C(posse_de_imovel, Treatment(True)) +
C(tipo_renda, Treatment('Assalariado')) +
C(educacao, Treatment('Secundário')) +
C(estado_civil, Treatment('Casado')) +
C(tipo_residencia, Treatment('Casa')) +
idade + tempo_emprego + qtd_filhos + qt_pessoas_residencia
"""

y, X = patsy.dmatrices(formula, df, return_type='dataframe')

model = sm.OLS(y, X).fit()
print(model.summary())

"""Os sinais dos coeficientes fazem sentido prático: níveis mais altos de escolaridade, tipo de renda empresarial e servidor público apresentaram coeficientes positivos, indicando maior renda quando comparados às categorias de referência.

A idade e o tempo de emprego mostraram efeitos positivos significativos, compatíveis com progressão profissional. Já a variável `qtd_filhos` apresentou coeficiente negativo, sugerindo que domicílios maiores estão associados a menor renda disponível.

No geral, o modelo apresenta coerência prática e estatística, com variáveis socioeconômicas mais associadas à estabilidade financeira contribuindo para maior renda.

Convém mencionar também que a categoria Pensionista foi a que apresentou o coeficiente mais negativo entre todas as categorias de tipo de renda (β = –0.3087). Em um modelo log-linear, isso corresponde a uma redução aproximada de 26,5% na renda, em comparação com trabalhadores assalariados, controlando por todas as demais variáveis. Esse resultado é coerente com o comportamento esperado, já que rendas provenientes de pensões tendem a ser menores e apresentam menor variabilidade associada a progressão de carreira.

2. Remova a variável menos significante e analise:
    - Observe os indicadores que vimos, e avalie se o modelo melhorou ou piorou na sua opinião.
    - Observe os parâmetros e veja se algum se alterou muito.
"""

# Retirando apenas o nível Primário, e não a variável educação inteira, porque
# ela tem níveis significantes (ex: Superior completo).

df2 = df[df['educacao'] != 'Primário'].copy()

formula2 = """
np.log(renda) ~
C(sexo, Treatment('F')) +
C(posse_de_veiculo, Treatment(False)) +
C(posse_de_imovel, Treatment(True)) +
C(tipo_renda, Treatment('Assalariado')) +
C(educacao, Treatment('Secundário')) +
C(estado_civil, Treatment('Casado')) +
C(tipo_residencia, Treatment('Casa')) +
idade + tempo_emprego + qtd_filhos + qt_pessoas_residencia
"""

y2, X2 = patsy.dmatrices(formula2, df2, return_type='dataframe')
model2 = sm.OLS(y2, X2).fit()
print(model2.summary())

"""Após a remoção da categoria Primário da variável educação (por ser a menos significativa, com um p-value de 0.844), ocorreram algumas mudanças pequenas: o R² aumentou de 0.357 para 0.358, o AIC diminuiu de 27 190 para 26 980. Por outro lado, o R² ajustado permaneceu igual. Os p-values das demais variáveis sofreram alterações muito pequenas.

A meu ver, nenhum coeficiente relevante sofreu alteração substancial e nenhuma variável significativa deixou de ser significativa após a remoção. Todas as relações principais permaneceram estáveis, indicando que Primário não contribuía para explicar a renda e apenas adicionava ruído.

Portanto, o segundo modelo é de certa forma melhor, pois mantém praticamente o mesmo poder explicativo, mas é mais simples e apresenta métricas de ajuste superiores, alinhado ao princípio da parcimônia.

3. Siga removendo as variáveis menos significantes, sempre que o *p-value* for menor que 5%. Compare o modelo final com o inicial. Observe os indicadores e conclua se o modelo parece melhor.
"""

# As próximas variáveis a sair são:

# 1 - C(educacao, Treatment('Secundário'))[T.Primário]
# 2 - C(tipo_residencia, Treatment('Casa'))[T.Governamental]         0.635
# 3 - C(tipo_residencia, Treatment('Casa'))[T.Com os pais]            0.594
# 4 - C(tipo_residencia, Treatment('Casa'))[T.Comunitário]           0.493
# 5 - C(educacao, Treatment('Secundário'))[T.Pós graduação]           0.398
# 6 - C(educacao, Treatment('Secundário'))[T.Superior incompleto]    0.360
# 7 - C(tipo_residencia, Treatment('Casa'))[T.Aluguel]                0.358
# 8 - C(tipo_renda, Treatment('Assalariado'))[T.Bolsista]             00.356
# 9 - C(tipo_renda, Treatment('Assalariado'))[T.Pensionista]         0.199
# 10 - C(tipo_residencia, Treatment('Casa'))[T.Estúdio]                0.194
# 11 - C(estado_civil, Treatment('Casado'))[T.União]                 0.122

df3 = df3[df3['educacao'] != 'Primário'].copy() # 1
df3 = df3[df3['tipo_residencia'] != 'Governamental'].copy() # 2
df3 = df3[df3['tipo_residencia'] != 'Com os pais'].copy() # 3
df3 = df3[df3['tipo_residencia'] != 'Comunitário'].copy() # 4
df3 = df3[df3['educacao'] != 'Pós graduação'].copy() # 5
df3 = df3[df3['educacao'] != 'Superior incompleto'].copy() # 6
df3 = df3[df3['tipo_residencia'] != 'Aluguel'].copy() # 7
df3 = df3[df3['tipo_renda'] != 'Bolsista'].copy() # 8
df3 = df3[df3['tipo_renda'] != 'Pensionista'].copy() # 9
df3 = df3[df3['tipo_residencia'] != 'Estúdio'].copy() # 10
df3 = df3[df3['estado_civil'] != 'União'].copy() # 11

formula3 = """
np.log(renda) ~
C(sexo, Treatment('F')) +
C(posse_de_veiculo, Treatment(False)) +
C(posse_de_imovel, Treatment(True)) +
C(tipo_renda, Treatment('Assalariado')) +
C(educacao, Treatment('Secundário')) +
C(estado_civil, Treatment('Casado')) +
C(tipo_residencia, Treatment('Casa')) +
idade + tempo_emprego + qtd_filhos + qt_pessoas_residencia
"""

y3, X3 = patsy.dmatrices(formula3, df3, return_type='dataframe')
model3 = sm.OLS(y3, X3).fit()
print(model3.summary())

"""- R² -> Modelo 1: 0.357 | Modelo final: 0.363;
- R² ajustado -> Modelo 1: 0.356 | Modelo final: 0.363;
- AIC -> Modelo inicial: 27 190 | Modelo final: 21 390;
- Nº variáveis -> Modelo inicial:	24 | Modelo final: 13	(modelo mais simples).

As variáveis que restaram (que são mais relevantes) condizem muito com a realidade socioeconômica do Brasil:

- Homens em geral ganham mais;
- Donos de veículo ganham mais, assim como quem tem imóvel;
- Empresários ganham mais;
- Servidores públicos têm renda um pouco maior;
- Superior completo faz bastante diferença no mercado de trabalho;
- Separados, solteiros e viúvos ganham mais;
- Idade aumenta renda gradualmente;
- Tempo de emprego é o preditor mais forte;
- Ter mais filhos indica uma renda menor, em geral.

Assim, o modelo final é mais parcimonioso, mais robusto e apresenta melhor capacidade preditiva do que o modelo inicial. O processo de refinamento permitiu identificar as variáveis realmente explicativas da renda, resultando em um modelo estatística e conceitualmente superior.
"""