# -*- coding: utf-8 -*-
"""regularizacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z6VF2HZzYuQjAjSlWgi5WBt0X-Ded0hV
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
import statsmodels.api as sm
import patsy
# from io import StringIO

# %matplotlib inline

# # Tive que criar a base de dados do 0, por conta de algum problema interno
# # que está impedindo o seaborn de importá-la

# tips_csv = """
# total_bill,tip,sex,smoker,day,time,size
# 16.99,1.01,Female,No,Sun,Dinner,2
# 10.34,1.66,Male,No,Sun,Dinner,3
# 21.01,3.5,Male,No,Sun,Dinner,3
# 23.68,3.31,Male,No,Sun,Dinner,2
# 24.59,3.61,Female,No,Sun,Dinner,4
# 25.29,4.71,Male,No,Sun,Dinner,4
# 8.77,2.0,Female,No,Sun,Dinner,2
# 26.88,3.12,Male,No,Sun,Dinner,4
# 15.04,1.96,Male,No,Sun,Dinner,2
# 14.78,3.23,Male,No,Sun,Dinner,2
# 10.27,1.71,Male,No,Sun,Dinner,2
# 35.26,5.0,Female,No,Sun,Dinner,4
# 15.42,1.57,Male,No,Sun,Dinner,2
# 18.43,3.0,Male,No,Sun,Dinner,4
# 14.83,3.02,Female,No,Sun,Dinner,2
# 21.58,3.92,Male,No,Sun,Dinner,2
# 10.33,1.67,Female,No,Sun,Dinner,3
# 16.29,3.71,Female,Yes,Sun,Dinner,3
# 16.97,3.5,Female,No,Sun,Dinner,3
# 20.65,3.35,Male,No,Sat,Dinner,3
# 17.92,4.08,Male,No,Sat,Dinner,2
# 20.29,2.75,Female,No,Sat,Dinner,2
# 15.77,2.23,Female,No,Sat,Dinner,2
# 39.42,7.58,Male,No,Sat,Dinner,4
# 19.82,3.18,Male,No,Sat,Dinner,2
# 17.81,2.34,Male,No,Sat,Dinner,4
# 13.37,2.0,Male,No,Sat,Dinner,2
# 12.69,2.0,Male,No,Sat,Dinner,2
# 21.7,4.3,Male,No,Sat,Dinner,2
# 19.65,3.0,Male,No,Sat,Dinner,2
# 9.55,1.45,Male,No,Sat,Dinner,2
# 18.35,2.5,Female,No,Sat,Dinner,4
# 15.06,3.0,Female,No,Sat,Dinner,2
# 20.69,2.45,Female,No,Sat,Dinner,4
# 17.78,3.27,Male,No,Sat,Dinner,2
# 24.06,3.6,Male,No,Sat,Dinner,3
# 16.31,2.0,Female,No,Sat,Dinner,3
# 16.93,3.07,Female,No,Sat,Dinner,3
# 18.69,2.31,Male,No,Sun,Dinner,3
# 31.27,5.0,Male,Yes,Sun,Dinner,3
# 16.04,2.24,Male,No,Sun,Dinner,3
# 17.46,2.54,Female,No,Sun,Dinner,2
# 13.94,3.06,Female,No,Sun,Dinner,2
# 9.68,1.32,Male,Yes,Sun,Dinner,2
# 30.4,5.6,Male,Yes,Sun,Dinner,4
# 18.29,3.0,Male,Yes,Sun,Dinner,2
# 22.23,5.0,Male,Yes,Sun,Dinner,2
# 32.4,6.0,Male,Yes,Sun,Dinner,4
# 28.55,2.05,Male,Yes,Sun,Dinner,3
# 18.04,3.0,Unknown,No,Sun,Dinner,2
# 12.54,2.5,Female,No,Sun,Dinner,2
# 10.29,2.2,Male,No,Sun,Dinner,2
# 34.81,5.2,Female,No,Sun,Dinner,4
# 9.94,1.56,Male,No,Sun,Dinner,2
# 25.56,4.34,Male,No,Sun,Dinner,4
# 19.49,3.51,Male,No,Sun,Dinner,2
# 38.01,3.0,Male,Yes,Sat,Dinner,4
# 26.41,1.5,Female,No,Sat,Dinner,2
# 11.24,1.76,Female,No,Sat,Dinner,2
# 48.27,6.73,Male,No,Sat,Dinner,4
# 20.29,3.21,Male,Yes,Sat,Dinner,2
# 13.81,2.0,Male,Yes,Sat,Dinner,2
# 11.02,1.98,Male,Yes,Sat,Dinner,2
# 18.29,3.76,Male,Yes,Sat,Dinner,4
# 17.59,2.64,Male,No,Sat,Dinner,3
# 20.08,3.15,Male,Yes,Sat,Dinner,3
# 16.45,2.47,Female,No,Sat,Dinner,2
# 3.07,1.0,Female,Yes,Sat,Dinner,1
# 20.23,2.01,Male,No,Sat,Dinner,2
# 15.01,2.09,Female,Yes,Sat,Dinner,2
# 12.02,1.97,Male,No,Sat,Dinner,2
# 17.07,3.0,Male,No,Sat,Dinner,3
# 26.86,3.14,Male,No,Sat,Dinner,2
# 25.28,5.0,Female,No,Sat,Dinner,2
# 14.73,2.2,Female,No,Sat,Dinner,2
# 10.51,1.25,Male,No,Sat,Dinner,2
# 17.92,3.0,Male,No,Sat,Dinner,2
# 27.2,4.0,Male,No,Sat,Dinner,4
# 22.76,3.0,Male,No,Sat,Dinner,2
# 17.29,2.71,Female,No,Sat,Dinner,2
# 19.44,3.0,Male,Yes,Sat,Dinner,2
# 16.66,3.0,Female,Yes,Sat,Dinner,2
# 20.53,2.0,Male,Yes,Sat,Dinner,2
# 8.51,1.25,Female,Yes,Sat,Dinner,2
# 18.35,2.5,Male,Yes,Sat,Dinner,4
# 16.82,4.0,Male,Yes,Sat,Dinner,2
# 32.08,5.0,Male,Yes,Sat,Dinner,2
# 17.41,3.0,Female,Yes,Sat,Dinner,2
# 18.64,1.36,Female,Yes,Sat,Dinner,3
# 11.87,1.63,Male,Yes,Sat,Dinner,2
# 36.0,3.0,Male,Yes,Sat,Dinner,3
# 15.38,1.5,Male,Yes,Sat,Dinner,2
# 16.24,2.0,Male,Yes,Sat,Dinner,2
# 13.42,3.48,Female,Yes,Sat,Dinner,2
# 18.43,1.86,Male,Yes,Sat,Dinner,2
# 25.0,4.0,Male,Yes,Sat,Dinner,4
# 24.01,2.0,Male,Yes,Sat,Dinner,3
# 21.0,3.0,Male,Yes,Sat,Dinner,3
# 28.97,3.0,Male,Yes,Sat,Dinner,2
# 22.49,3.5,Female,Yes,Sat,Dinner,2
# 5.75,1.0,Female,Yes,Sat,Dinner,2
# 16.32,4.3,Female,Yes,Sat,Dinner,2
# 22.75,3.25,Female,Yes,Sat,Dinner,2
# 18.35,3.5,Male,Yes,Sat,Dinner,2
# 24.01,3.0,Female,Yes,Sat,Dinner,4
# 21.16,3.0,Male,Yes,Sat,Dinner,2
# 28.97,3.0,Female,Yes,Sat,Dinner,2
# 12.9,1.1,Male,Yes,Sat,Dinner,2
# 28.15,3.0,Male,Yes,Sat,Dinner,5
# 11.59,1.5,Male,Yes,Sat,Dinner,2
# 7.74,1.44,Male,Yes,Sat,Dinner,2
# 30.14,3.09,Male,Yes,Sat,Dinner,4
# 12.16,2.2,Male,Yes,Sat,Dinner,2
# 13.42,3.48,Female,No,Thur,Lunch,2
# 8.58,1.92,Male,No,Thur,Lunch,1
# 15.98,3.0,Male,No,Thur,Lunch,3
# 13.42,1.58,Male,No,Thur,Lunch,2
# 16.27,2.5,Female,No,Thur,Lunch,2
# 10.09,2.0,Male,No,Thur,Lunch,2
# 20.45,3.0,Male,No,Thur,Lunch,4
# 13.28,2.72,Male,No,Thur,Lunch,2
# 22.12,2.88,Male,Yes,Thur,Lunch,2
# 24.01,2.52,Male,No,Thur,Lunch,4
# 15.69,3.0,Female,Yes,Thur,Lunch,3
# 11.61,3.39,Female,Yes,Thur,Lunch,2
# 10.77,1.47,Female,Yes,Thur,Lunch,2
# 15.53,3.0,Male,No,Thur,Lunch,2
# 10.07,1.25,Male,No,Thur,Lunch,2
# 12.6,1.0,Male,Yes,Thur,Lunch,2
# 32.83,1.17,Male,Yes,Thur,Lunch,2
# 35.83,4.67,Female,No,Thur,Lunch,3
# 29.03,5.92,Male,No,Thur,Lunch,3
# 27.18,2.0,Female,Yes,Thur,Lunch,2
# 22.67,2.0,Male,No,Thur,Lunch,2
# 17.82,1.75,Female,No,Thur,Lunch,2
# 18.78,3.0,Female,No,Thur,Lunch,2
# 17.89,2.0,Female,No,Thur,Lunch,2
# 52.34,5.0,Male,No,Thur,Lunch,3
# 18.71,4.0,Male,No,Thur,Lunch,3
# 16.94,3.0,Female,No,Thur,Lunch,2
# 26.41,1.5,Male,Yes,Fri,Dinner,2
# 18.43,1.57,Male,Yes,Fri,Dinner,2
# 14.83,3.02,Female,Yes,Fri,Dinner,2
# 12.8,2.2,Female,Yes,Fri,Dinner,2
# 13.37,2.0,Male,Yes,Fri,Dinner,2
# 16.27,2.5,Female,Yes,Fri,Dinner,2
# 22.0,3.25,Male,Yes,Fri,Dinner,2
# 15.98,3.0,Male,Yes,Fri,Dinner,3
# 13.42,3.48,Female,Yes,Fri,Dinner,2
# 16.27,3.0,Female,Yes,Fri,Dinner,2
# 10.09,2.0,Female,Yes,Fri,Dinner,2
# 20.45,3.0,Male,Yes,Fri,Dinner,4
# 13.28,2.72,Male,Yes,Fri,Dinner,2
# 22.12,2.88,Female,Yes,Fri,Dinner,2
# 24.01,2.52,Female,Yes,Fri,Dinner,4
# 15.69,3.0,Female,Yes,Fri,Dinner,3
# 11.61,3.39,Female,Yes,Fri,Dinner,2
# 7.25,1.0,Male,No,Fri,Dinner,1
# 31.85,3.18,Male,No,Fri,Dinner,2
# 16.82,4.0,Male,No,Fri,Dinner,2
# 24.52,3.48,Male,No,Fri,Dinner,3
# 20.76,2.24,Female,No,Fri,Dinner,2
# 31.71,4.5,Male,No,Fri,Dinner,4
# 10.59,1.61,Female,No,Fri,Dinner,2
# 10.63,2.0,Male,No,Fri,Dinner,2
# 50.81,10.0,Male,Yes,Fri,Dinner,3
# 15.81,3.16,Male,Yes,Fri,Dinner,2
# 7.25,1.0,Male,Yes,Fri,Dinner,2
# 31.85,3.18,Male,Yes,Fri,Dinner,2
# 16.82,4.0,Female,Yes,Fri,Dinner,2
# 32.68,5.0,Male,Yes,Fri,Dinner,2
# 15.98,3.0,Female,Yes,Fri,Dinner,3
# 13.42,3.48,Female,Yes,Fri,Dinner,2
# 16.27,3.0,Female,Yes,Fri,Dinner,2
# 10.09,2.0,Female,Yes,Fri,Dinner,2
# 20.45,3.0,Male,Yes,Fri,Dinner,4
# 13.28,2.72,Male,Yes,Fri,Dinner,2
# 22.12,2.88,Female,Yes,Fri,Dinner,2
# 24.01,2.52,Female,Yes,Fri,Dinner,4
# 15.69,3.0,Female,Yes,Fri,Dinner,3
# 11.61,3.39,Female,Yes,Fri,Dinner,2
# 10.0,1.5,Male,No,Fri,Dinner,2
# 12.46,1.5,Male,No,Fri,Dinner,2
# 11.35,2.5,Female,No,Fri,Dinner,2
# 15.38,3.0,Female,No,Fri,Dinner,2
# 44.3,2.5,Female,No,Fri,Dinner,3
# 22.42,3.48,Female,No,Fri,Dinner,2
# 20.92,4.08,Female,No,Fri,Dinner,2
# 15.36,1.64,Male,No,Fri,Dinner,2
# 20.49,4.06,Male,Yes,Fri,Dinner,2
# 25.21,4.29,Male,Yes,Fri,Dinner,2
# 18.24,3.76,Male,Yes,Fri,Dinner,3
# 14.31,3.0,Female,Yes,Fri,Dinner,3
# 14.0,2.5,Male,No,Fri,Dinner,2
# 7.25,1.0,Male,No,Fri,Dinner,1
# 38.01,3.0,Male,No,Fri,Dinner,4
# 23.01,3.0,Male,Yes,Fri,Dinner,2
# 17.4,3.0,Female,Yes,Fri,Dinner,3
# 15.01,2.09,Female,Yes,Fri,Dinner,2
# 12.02,1.97,Male,Yes,Fri,Dinner,2
# 20.45,3.0,Male,Yes,Fri,Dinner,4
# 13.28,2.72,Male,Yes,Fri,Dinner,2
# 12.6,1.0,Male,Yes,Thur,Lunch,2
# 32.83,1.17,Male,Yes,Thur,Lunch,2
# 35.83,4.67,Female,No,Thur,Lunch,3
# 29.03,5.92,Male,No,Thur,Lunch,3
# 27.18,2.0,Female,Yes,Thur,Lunch,2
# 22.67,2.0,Male,No,Thur,Lunch,2
# 17.82,1.75,Female,No,Thur,Lunch,2
# 18.78,3.0,Female,No,Thur,Lunch,2
# 17.89,2.0,Female,No,Thur,Lunch,2
# 52.34,5.0,Male,No,Thur,Lunch,3
# 18.71,4.0,Male,No,Thur,Lunch,3
# 16.94,3.0,Female,No,Thur,Lunch,2
# 26.41,1.5,Male,Yes,Fri,Dinner,2
# 18.43,1.57,Male,Yes,Fri,Dinner,2
# 14.83,3.02,Female,Yes,Fri,Dinner,2
# 12.8,2.2,Female,Yes,Fri,Dinner,2
# 13.37,2.0,Male,Yes,Fri,Dinner,2
# 16.27,2.5,Female,Yes,Fri,Dinner,2
# 22.0,3.25,Male,Yes,Fri,Dinner,2
# 15.98,3.0,Male,Yes,Fri,Dinner,3
# 13.42,3.48,Female,Yes,Fri,Dinner,2
# 16.27,3.0,Female,Yes,Fri,Dinner,2
# 10.09,2.0,Female,Yes,Fri,Dinner,2
# 20.45,3.0,Male,Yes,Fri,Dinner,4
# 13.28,2.72,Male,Yes,Fri,Dinner,2
# 22.12,2.88,Female,Yes,Fri,Dinner,2
# 24.01,2.52,Female,Yes,Fri,Dinner,4
# 15.69,3.0,Female,Yes,Fri,Dinner,3
# 11.61,3.39,Female,Yes,Fri,Dinner,2
# """

# tips = pd.read_csv(StringIO(tips_csv))

tips = sns.load_dataset("tips")
tips['tip_pct'] = tips['tip'] / (tips['total_bill'] - tips['tip'])
tips['net_bill'] = tips['total_bill'] - tips['tip']
tips.head()

# Usando a regularização Lasso para fazer a seleção de vários modelos

modelo = 'np.log(tip) ~ C(size) + np.log(net_bill) + smoker + time + day'
md = smf.ols(modelo, data=tips)
reg = md.fit_regularized(method='elastic_net',
                         refit=True, # Essa opção faz com que o modelo seja
                                     # automaticamente "fitado", caso alguma
                                     # variável seja zerada
                         L1_wt=1, # Considerando-se a fórmula do método
                                  # elastic_net, ele utiliza tanto a função
                                  # lasso quanto a função ridge. Esse parâmetro
                                  # faz com que todo o peso esteja na função
                                  # lasso e nenhum esteja no ridge
                         alpha=0.01)
reg.summary()
