# -*- coding: utf-8 -*-
"""simulando_a_distribuicao_de_beta_chapeu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z8R7-hMJVIip9DkwyDZVExt2S7iQOayF
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
import statsmodels.api as sm
import patsy

# %matplotlib inline

plt.rc('figure', figsize=(6,4))
N = 50

x = np.linspace(0, 8, N)
y = 5 + .1 * x + np.random.randn(N) * .5

df1 = pd.DataFrame({'x': x, 'y': y})

fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)

_ = sns.regplot(x='x', y='y', data=df1, ax=ax)
ax.set_xlim(0, 8)
ax.set_ylim(3, 8)
ticks = ax.set_xticks(list(range(0, 9, 1)))
ticks = ax.set_yticks(list(range(3, 9, 1)))

print(df1.corr())

reg = smf.ols('y ~ x', data=df1).fit()
reg.summary()

betas = []

for i in range(2000):
  x = np.linspace(0, 8, N)
  y = .1 * x + np.random.randn(N) * .5
  df1 = pd.DataFrame({'x': x, 'y': y})
  reg = smf.ols('y ~ x', data=df1).fit()
  betas.append(reg.params[1])

plt.rc('figure', figsize=(20, 10))
g = sns.displot([betas], binwidth=.005, height=5, aspect=1.5)
g.set(xlim=(0, 0.2), ylim=(0, 170))

betas = []

for i in range(2000):
  x = np.linspace(0, 8, N)
  y = 0 * x + np.random.randn(N) * .5
  df1 = pd.DataFrame({'x': x, 'y': y})
  reg = smf.ols('y ~ x', data=df1).fit()
  betas.append(reg.params[1])

plt.rc('figure', figsize=(20, 10))
g = sns.displot([betas], binwidth=.005, height=5, aspect=1.5)
g.set(xlim=(-0.15, 0.15), ylim=(0, 170))

N = 50

x = np.linspace(0, 8, N)
y = 5 + .1 * x + np.random.randn(N) * .5

df1 = pd.DataFrame({'x': x, 'y': y})

_ = sns.regplot(x='x', y='y', data=df1)
print(df1.corr())

reg = smf.ols('y ~ x', data=df1).fit()
reg.summary()

betas = []

for i in range(2000):
    x = np.linspace(0, 8, N)
    y = 0 * x + np.random.randn(N) * .5
    df1 = pd.DataFrame({'x': x, 'y': y})
    reg = smf.ols('y ~ x', data=df1).fit()
    betas.append(reg.params[1])

sns.displot(betas)