# -*- coding: utf-8 -*-
"""apply_do_groupby.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wUDgelkXq7zhrJfKBJTMpFZ6V8vRZz2N
"""

import numpy as np
import pandas as pd

sinasc = pd.read_csv('SINASC_RO_2019.csv')
sinasc.head()

sinasc_2 = sinasc[['ESCMAE', 'IDADEMAE', 'IDADEPAI', 'QTDFILVIVO', 'QTDFILMORT']]
sinasc_2.head()

"""### Método apply"""

# Essa função irá pegar as 5 linhas com os maiores valores

def top(df, n=5, column='QTDFILVIVO'):
  return df.fillna(0).sort_values(by=column, ascending=False)[:n]

top(sinasc_2)

# Quais são as linhas que possuem a maior quantidade de filhos vivos?
# Para cada faixa de escolaridade da mãe, obtemos os top 5 quantidade de filhos
# vivos

sinasc_2.groupby('ESCMAE').apply(top)

# Podemos passar também os argumentos da função dentro do método apply
# Aqui estamos selecionando, para cada faixa de escolaridade da mãe, os top 6
# linhas com maior quantidade de filhos mortos

sinasc_2.groupby('ESCMAE').apply(top, n=6, column='QTDFILMORT')