# -*- coding: utf-8 -*-
"""m09_tarefa_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cQw-TXncID05JXiiTn6EK-Ai0icoFKXa
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# %matplotlib inline

sinasc = pd.read_csv('SINASC_RO_2019.csv')
sinasc.head()

sinasc.columns

"""# Tarefa 1

### 1. Idade media das mães e dos pais por município (coluna munResNome)
"""

sinasc.groupby('munResNome').agg({'IDADEMAE': 'mean', 'IDADEPAI': 'mean'}).rename(columns={'IDADEMAE': 'Idade Média das Mães', 'IDADEPAI': 'Idade Média dos Pais'})

"""### 2. Peso médio dos bebes por sexo que nasceram no dia do seu aniversário por faixas de escolaridade mae
Ex: Você, aluna(o), nasceu no dia 10/01, então você precisa filtrar o conjunto de dados nessa data e calcular o peso médio dos bebês de cada sexo por faixa de escolaridade da mãe.
"""

sinasc['DTNASC'] = pd.to_datetime(sinasc['DTNASC'])

sinasc_dt_aniversario = sinasc[sinasc['DTNASC'] == '2019-12-09']

sinasc_dt_aniversario.groupby(['SEXO', 'ESCMAE']).agg({'PESO': 'mean'}).rename(columns={'PESO': 'Peso Médio'})

"""### 3. Qual o municipio que nasceu menos bebe em 2019?
    - qual a idade media, maxima, minima das maes nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?
"""

nascimentos_por_mun = sinasc.groupby('munResNome', as_index=False).agg({'DTNASC': 'count'}).rename(columns={'DTNASC': 'Número de Nascimentos'})

# Município com menos nascimentos
mun_menos_bebes = nascimentos_por_mun.loc[nascimentos_por_mun['Número de Nascimentos'].idxmin(), 'munResNome']

# Estatísticas de idade nesse município
sinasc[sinasc['munResNome'] == mun_menos_bebes].agg({
        'IDADEMAE': ['mean', 'max', 'min'],
        'IDADEPAI': ['mean', 'max', 'min']
    })

"""### 4. Qual o municipio que nasceu mais bebe no mês de março?
    - qual a quantidade de filhos vivos media, maxima, minima nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?


"""

sinasc['MES'] = sinasc['DTNASC'].dt.month
sinasc_marco = sinasc[sinasc['MES'] == 3]

nasc_marco = sinasc_marco.groupby('munResNome', as_index=False).agg({'DTNASC': 'count'}).rename(columns={'DTNASC': 'Número de Bebês Nascidos em Março'})

mun_mais_marco = nasc_marco.loc[nasc_marco['Número de Bebês Nascidos em Março'].idxmax(), 'munResNome']

sinasc_marco[sinasc_marco['munResNome'] == mun_mais_marco].agg({
        'QTDFILVIVO': ['mean', 'max', 'min'],
        'IDADEPAI': ['mean', 'max', 'min']
    })

"""### Analise as respostas encontradas, tire algum insight delas, conte pra gente algo encontrado nos dados. Algo que você julgue relevante e novo pra você.

Exemplo:
- Ah, descobri que a idade mediana das mulheres que deram a luz no ano de 2019 dos municipios x é maior que y.
"""

sinasc.dtypes

sinasc.select_dtypes(exclude=['int64','float64'])

sinasc_raw.columns