# -*- coding: utf-8 -*-
"""baixe_dados_da_bolsa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i9FpF0nKZQe9Y_CqEy0cNNAxBwBAI9mf
"""

!pip install pandas_datareader

!pip install yfinance

from pandas_datareader import data as web
import plotly.express as px
from plotly import graph_objects
import yfinance as yf
import pandas as pd
import numpy as np

ativos = '^BVSP'
dt_ini, dt_fim = '2021-01-01', '2021-07-01'

df_bvsp = yf.Ticker(ativos).history(start=dt_ini, end=dt_fim)
df_bvsp = df_bvsp[['High', 'Low', 'Open', 'Close', 'Volume', 'Close']]
df_bvsp.columns = ['High', 'Low', 'Open', 'Close', 'Volume', 'Adj Close']
df_bvsp.head()

ativos = ['^BVSP', 'ITUB3.SA', 'PETR4.SA', 'ABEV3.SA', 'VALE3.SA']
dt_ini = '2016-01-01'

df_ativos = yf.download(ativos, start=dt_ini)
df_ativos.head()

df_ativos.columns

df_ativos[( 'Close', 'ABEV3.SA')]

df_ativos['Close']

df_ativos['Close'].isna().sum()

fechamento_vertical = df_ativos['Close'].stack().reset_index()
fechamento_vertical.columns = ['Data', 'Ativo', 'Valor']
fechamento_vertical.head()
