# -*- coding: utf-8 -*-
"""calcule_o_retorno_de_series_parte_II.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kEQNR8g4PAtKAw8BNlOP5q4sfw36LcLd
"""

import plotly.express as px
from plotly import graph_objects
import yfinance as yf
import pandas as pd
import numpy as np

ativos = ['^BVSP', 'ITUB3.SA', 'PETR4.SA', 'ABEV3.SA', 'VALE3.SA']
dt_ini = '2016-01-01'

df_ativos = yf.download(ativos, start=dt_ini)
df_ativos.head()

ativos_diff = df_ativos['Close'].copy().diff()
ativos_diff['Ano'] = df_ativos.reset_index().Date.dt.year.astype('str').values

fig = px.scatter(ativos_diff, x='^BVSP', y='PETR4.SA', color='Ano', marginal_y='box',
                 marginal_x='violin', trendline='ols', template='simple_white')
fig.show()

df_volume = df_ativos['Volume']
df_volume_vertical = df_volume.stack().reset_index()
df_volume_vertical.columns = ['Data', 'Ativo', 'Valor']
df_volume_vertical.head()

df_volume_vertical['Ano'] = df_volume_vertical.Data.dt.year.values
df_agrupado = df_volume_vertical.groupby(['Ano', 'Ativo'])['Valor'].sum().reset_index()
df_agrupado.head()

fig = px.sunburst(df_agrupado, path=['Ativo', 'Ano'], values='Valor')
fig.show()
