# -*- coding: utf-8 -*-
"""calcule_o_retorno_de_series_parte_I.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fQsSLxLSFpWK9zhLMRIGo5Vobrq9eUYR
"""

import plotly.express as px
from plotly import graph_objects
import yfinance as yf
import pandas as pd
import numpy as np

ativos = ['^BVSP', 'ITUB3.SA', 'PETR4.SA', 'ABEV3.SA', 'VALE3.SA']
dt_ini = '2016-01-01'

df_ativos = yf.download(ativos, start=dt_ini)
df_ativos.head()

P1 = 42141.0
P2 = 42419.0

R = (P2 - P1) / P1
R

df_retornos = df_ativos['Close'].pct_change()
df_retornos.head()

df_retornos_vertical = df_retornos.stack().reset_index()
df_retornos_vertical.columns = ['Data', 'Ativo', 'Retorno']

fig = px.line(df_retornos_vertical, x='Data', y='Retorno', color='Ativo')
fig.show()