# -*- coding: utf-8 -*-
"""crie_grafico_de_candlestick.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KIOvK7e_nZkpRO_nZL55UnPrXzXIYPSO
"""

import plotly.express as px
from plotly import graph_objects
import yfinance as yf
import pandas as pd
import numpy as np

ativos = ['^BVSP', 'ITUB3.SA', 'PETR4.SA', 'ABEV3.SA', 'VALE3.SA']
dt_ini = '2016-01-01'

df_ativos = yf.download(ativos, start=dt_ini)
df_ativos.head()

df_ativos.columns

lista_indicadores = ['Close', 'High', 'Low', 'Open', 'Volume']
ativo = ['^BVSP'] * len(lista_indicadores)

colunas = list(zip(lista_indicadores, ativo))
colunas

bvsp = df_ativos.loc['2025-09-20':, colunas] # do dia pra frente
bvsp.columns = lista_indicadores
bvsp.head()

graph = {
    'x': bvsp.index,
    'open': bvsp.Open,
    'close': bvsp.Close,
    'high': bvsp.High,
    'low': bvsp.Low,
    'type': 'candlestick',
    'name': '^BVSP',
    'showlegend': True
}

from plotly import graph_objects
from plotly.graph_objects import Layout

layout = Layout(
    paper_bgcolor='rgba(255,255,255,1)',
    plot_bgcolor='rgba(255,255,255,1)'
)

grafico = graph_objects.Figure(
    data=[graph],
    layout_title='Índice Bovespa',
    layout=layout
)

grafico.update_xaxes(showgrid=True, gridwidth=1, gridcolor='LightGrey')
grafico.update_yaxes(showgrid=True, gridwidth=1, gridcolor='LightGrey')

grafico.show()