# -*- coding: utf-8 -*-
"""m22_tarefa_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mio6wP5KhkUY7OoBgY6OZ8ile9TgoQj2

# Tarefa 01

- Leia os enunciados com atenção
- Saiba que pode haver mais de uma resposta correta
- Insira novas células de código sempre que achar necessário
- Em caso de dúvidas, procure os monitores
- Divirta-se :)

#### 1. Baixando dados de ativos
    1. Baixe os dados de três ativos da sua escolha do Yahoo Finance, correspondente a um período de pelo menos 2 anos até a data mais recente.
    2. Salve esses dados para que você possa utilizá-los na próxima tarefa.
"""

import plotly.express as px
from plotly import graph_objects
import yfinance as yf
import pandas as pd
import numpy as np

ativos = ['AAPL', 'GOOGL', 'MSFT']
dt_ini = '2024-01-01'

df_ativos = yf.download(ativos, start=dt_ini)
df_ativos.head()

df_ativos.to_csv('ativos.csv')

"""#### 2. Observando a volatilidade dentro do dia
1. Calcule a amplitude de variação do valor do ativo dentro do dia. Essa amplitude você pode calcular com um comando simples de adicionar uma coluna no Pandas: (valor máximo - valor mínimo).
2. Monte um gráfico de linha mostrando a variação dessa amplitude ao longo do período coletado, por ativo.
3. Veja se consegue identificar que ativo apresentou maior volatilidade.
"""

amplitudes = []

for ativo in ativos:
    temp = pd.DataFrame({
        'Ativo': ativo,
        'Amplitude': df_ativos[('High', ativo)] - df_ativos[('Low', ativo)]
    })

    amplitudes.append(temp)

df_amp = pd.concat(amplitudes)
df_amp.head()

fig = px.line(df_amp, x=df_amp.index, y='Amplitude', color='Ativo',
              title='Amplitude diária (High - Low) por ativo')
fig.show()

"""A partir da análise do gráfico de amplitude diária, observa-se que o ativo da Microsoft (MSFT) apresentou, em média, maior volatilidade intradiária ao longo período analisado. Destaca-se um pico expressivo no mês de abril de 2025, indicando um aumento atípico da variação de preços dentro do dia.
Observa-se que esse pico ocorreu em todos os ativos, não apenas ao da Microsoft. Isso pode ser explicado pelo fato de que, em Abril de 2025, ocorreu o "2025 stock market crash", período em que os mercados de ações globais começaram a sofrer uma crise econômica significativa, resultante de tarifas e guerras comerciais iniciadas pelo presidente dos Estados Unidos, Donald Trump. É considerado o maior declínio no mercado de ações global desde a quebra do mercado de ações de 2020.
"""