# -*- coding: utf-8 -*-
"""m22_tarefa_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/144irb_Y50Us0CSrl-8hfx68W--Rhy4qS

# Tarefa 02

- Leia os enunciados com atenção
- Saiba que pode haver mais de uma resposta correta
- Insira novas células de código sempre que achar necessário
- Em caso de dúvidas, procure os monitores
- Divirta-se :)

#### 1. Carregue os dados da tarefa anterior
"""

import plotly.express as px
from plotly import graph_objects
import yfinance as yf
import pandas as pd
import numpy as np

df_ativos = pd.read_csv('ativos.csv',
                        header=[0, 1], # Duas linhas de cabeçalho (MultiIndex)
                        index_col=0, # Primeira coluna é a data
                        parse_dates=True) # Converte índice para DateTime
df_ativos.head()

"""#### 2. Média móvel

1. Faça uma média móvel  em 90 dias dos valores de fechamento ajustados dos ativos que você escolheu
2. Utilizando a fução ```rolling()```, calcule o desvio pardão desses ativos ao longo do tempo, utilizando a mesma janela móvel do item acima
2. Monte um gráfico de linhas para as médias móveis dos ativos da sua base
4. Monte um gráfico de linhas para os desvios padrão em janela móvel
5. Compare os dois gráficos que você fez com o da tarefa anterior. Veja se eles apontam conclusões semelhantes quanto aos períodos de maior volatilidade (variação) dos ativos.
"""

df_close = df_ativos['Close']
df_close.head()

mm_90 = df_close.rolling(90).mean()
mm_90.head(100)

std_90 = df_close.rolling(90).std()
std_90.head(100)

df_mm_90 = (mm_90.stack().reset_index())
df_mm_90.columns = ['Data', 'Ativo', 'Média Móvel 90 Dias']
df_mm_90.head()

fig = px.line(df_mm_90, x='Data', y='Média Móvel 90 Dias', color='Ativo')
fig.show()

df_std_90 = (std_90.stack().reset_index())
df_std_90.columns = ['Data', 'Ativo', 'STD 90 Dias']
df_std_90.head()

fig = px.line(df_std_90, x='Data', y='STD 90 Dias', color='Ativo')
fig.show()

"""A comparação entre os gráficos aponta conclusões semelhantes quanto aos períodos de maior volatilidade. Em especial, observa-se que a Microsoft (MSFT) apresentou o maior e mais persistente aumento de volatilidade ao longo de 2025, com destaque para o período entre abril e setembro. A Apple (AAPL) também apresentou aumento de volatilidade no mesmo intervalo, porém de forma mais moderada. Já o Google (GOOGL) apresentou um crescimento mais gradual da volatilidade, principalmente no final de 2025. Dessa forma, ambos os métodos confirmam padrões consistentes de instabilidade no período analisado.

#### 3. Gráfico de *candlestick*
1. Selecione o período dos últimos 60 dias (corridos) para um dos ativos da sua base
2. Monte um gráfico de *candlestick* para esses dados.
"""

from datetime import timedelta

ativo_escolhido = 'AAPL'

data_fim = df_ativos.index.max()
data_inicio = data_fim - pd.Timedelta(days=60)

df_candle = df_ativos.loc[data_inicio:data_fim]

open = df_candle['Open'][ativo_escolhido]
high = df_candle['High'][ativo_escolhido]
low = df_candle['Low'][ativo_escolhido]
close = df_candle['Close'][ativo_escolhido]

from plotly import graph_objects
from plotly.graph_objects import Layout

graph = graph_objects.Candlestick(
    x=df_candle.index,
    open=open,
    high=high,
    low=low,
    close=close,
    name=ativo_escolhido
)

layout = Layout(
    paper_bgcolor='rgba(255,255,255,1)',
    plot_bgcolor='rgba(255,255,255,1)'
)

grafico = graph_objects.Figure(
    data=[graph],
    layout_title=f'Candlestick - {ativo_escolhido} (Últimos 60 dias)',
    layout=layout
)

grafico.update_xaxes(showgrid=True, gridwidth=1, gridcolor='LightGrey')
grafico.update_yaxes(showgrid=True, gridwidth=1, gridcolor='LightGrey')

grafico.show()