# -*- coding: utf-8 -*-
"""suavize_series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yWdRp0g1HDKyQJQSSOWsfsWcAs-47xUx
"""

import plotly.express as px
from plotly import graph_objects
import yfinance as yf
import pandas as pd
import numpy as np

ativos = ['^BVSP', 'ITUB3.SA', 'PETR4.SA', 'ABEV3.SA', 'VALE3.SA']
dt_ini = '2016-01-01'

df_ativos = yf.download(ativos, start=dt_ini)
df_ativos.head()

datas = pd.date_range('2016-01-01', periods=14, freq='D')
ts = pd.Series(list(range(7)) * 2, index=datas)
ts

ts.resample('W', closed='right', label='left').ffill()

ts.resample('W', closed='right', label='left').mean()

ts.rolling(3).mean()

df_retornos = df_ativos['Close'].pct_change()
df_retornos.head()

df_retornos_ma360 = df_retornos.rolling(360).mean()
df_retornos_ma360_vertical = df_retornos_ma360.stack().reset_index()
df_retornos_ma360_vertical.columns = ['Data', 'Ativo', 'Valor']
df_retornos_ma360_vertical

fig = px.line(df_retornos_ma360_vertical, x='Data', y='Valor', color='Ativo')
fig.show()