# -*- coding: utf-8 -*-
"""utilize_o_pacote_plotly.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q9UNBVcZtyS5yHS8xpUhmjhRwSmHdAgZ
"""

import plotly.express as px
from plotly import graph_objects
import yfinance as yf
import pandas as pd
import numpy as np

fechamento_vertical = pd.read_csv('fechamento_vertical.csv')
fechamento_vertical.head()

fig = px.line(fechamento_vertical, x='Data', y='Valor', color='Ativo',
              template='simple_white')
fig.show()

