# -*- coding: utf-8 -*-
"""aplique_regressao_logistica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MX2alyGWD6ZLpChCINx34Uf0t_luUoaV
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

P = pd.Series(np.linspace(0.001, .999, 1000))
P

logito = np.log(P / (1 - P))
plt.plot(P, logito, 'r')
plt.xlabel('P')
plt.ylabel('Logito')
plt.show()

plt.plot(logito, P, 'r')
plt.xlabel('Logito')
plt.ylabel('P')
plt.show()

"""### Regressão logística com uma variável"""

titanic = sns.load_dataset("titanic")
titanic.head()

import statsmodels.formula.api as smf

reglog = smf.logit("survived ~ sex", data=titanic).fit()
reglog.summary()

reglog.params

reglog.params[0]

reglog.params[1]

eta = reglog.params[0] + reglog.params[1]
eta
# Isso é o mesmo que alpha + betax (onde x é a variável sex)

chance = np.exp(eta)
chance

prob = 1 / (1 + np.exp(-eta))
prob

titanic['predito'] = reglog.predict(titanic)
titanic.head()