# -*- coding: utf-8 -*-
"""bivariada.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uI18cw_AU4XwFBfLERMAfpG_Iut_T5yz
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

# %matplotlib inline

titanic = sns.load_dataset('titanic')

tab = pd.crosstab(titanic['sex'], titanic['survived'], margins=True)
tab

"""### Risco do evento"""

tab[0] # não sobreviventes

tab[1] # sobreviventes

tab['All']

tab['probabilidade_sobreviver'] = tab[1] / tab['All']
tab

tab['probabilidade_morrer'] = tab[0] / tab['All']
tab

"""### Odds (Chance)"""

tab['chance_sobreviver'] = tab[1] / tab[0]
tab

chance = 2.87 / 0.23
print(f'Chance de sobrevivência: {chance:.2f}')

"""### Razãod de chances"""

tab['RC_vs_homem'] = tab['chance_sobreviver'] / tab.loc['male', 'chance_sobreviver']
tab