# -*- coding: utf-8 -*-
"""use_mais_de_uma_variavel_parte_I.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KYH9fYvPD-i4dQYl5sUV4FjGmMsMH_qt
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf

titanic = sns.load_dataset('titanic')
titanic.head()

reglog = smf.logit("survived ~ sex + pclass", data=titanic).fit()
reglog.summary()

reglog = smf.logit("survived ~ sex + C(pclass)", data=titanic).fit()
reglog.summary()

eta = 2.2971 + (-2.6419) + (-1.9055)
eta

chance = np.exp(eta)
chance

probabilidade = 1 / (1 + np.exp(-eta))
probabilidade

np.exp(-2.6419)

# chance de sobrevivência do perfil masculino em relação ao perfil feminino

1 / np.exp(-2.6419)
# chance de sobrevivência da mulher com relação a uma pessoa do perifl masculino

np.exp(-0.8380)

# chance de sobrevivência da segunda classe com relação à primeira

np.exp(-1.9055)

# chance de sobrevivência da terceira classe com relação à primeira

1 / np.exp(-0.8380)

# chance de sobrevivência da primeira classe com relação à segunda

1 / np.exp(-1.9055)

# chance de sobrevivência da primeira classe em relação à terceira