# -*- coding: utf-8 -*-
"""variaveis_continuas_parte_II.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SsZjULCjF8g0ZqQSBahW_XVIjJIwF1jd
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf

titanic = sns.load_dataset('titanic')
titanic.head()

reglog = smf.logit("survived ~ sex + fare", data=titanic).fit()
reglog.summary()

aumento_logito = 65 * 0.0112
aumento_logito

razao_de_chances = np.exp(-65 * 0.0112)
razao_de_chances

reglog = smf.logit("survived ~ sex + C(pclass) + fare", data=titanic).fit()
reglog.summary()