# -*- coding: utf-8 -*-
"""aplicacao_inicial_parte_II.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NSWllOMZUm8slU4cCAQj6Jvq4PgaiJES
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

bank_raw = pd.read_csv("/content/bank-additional-full.csv", sep=';')
bank = bank_raw.copy()

bank.job.unique().tolist()

jobs_list = bank.job.unique().tolist()
print(f"Profissões disponíveis: {jobs_list}")

jobs_selected = ['housemaid', 'services']
bank = bank[bank['job'].isin(jobs_selected)].reset_index(drop=True)

bank.head()