# -*- coding: utf-8 -*-
"""aplicacao_inicial_parte_III.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eu7lYidYcqx6usfzeG29MP4j2bL04G4c
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

bank_raw = pd.read_csv("/content/bank-additional-full.csv", sep=';')
bank = bank_raw.copy()

"""### Idade"""

max_age = int(bank.age.max())
min_age = int(bank.age.min())

print(f"Max age: {max_age}")
print(f"Min age: {min_age}")

idades = [min_age, max_age]
bank = bank[(bank['age'] >= idades[0]) & (bank['age'] <= idades[1])]

"""### Profissões"""

bank.job.unique().tolist()

jobs_list = bank.job.unique().tolist()
jobs_list.append('all')
print(f"Profissões disponíveis: {jobs_list}")

# jobs_selected = ['housemaid', 'services']
# bank = bank[bank['job'].isin(jobs_selected)].reset_index(drop=True)

jobs_selected = ['all']
jobs_selected

if 'all' in jobs_selected:
  pass
else:
  bank = bank[bank['job'].isin(jobs_selected)].reset_index(drop=True)