# -*- coding: utf-8 -*-
"""utilize_o_st_cache_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1znkZcT2ShiE1vIqc6OnqncyhVuojY3Lr
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

bank_raw = pd.read_csv("/content/bank-additional-full.csv", sep=';')
bank = bank_raw.copy()

bank.shape

bank_maior = pd.concat([bank] * 20, ignore_index=True)
bank_maior.shape

bank_maior.to_csv('bank_maior.csv', index=False, sep=';')