# -*- coding: utf-8 -*-
"""faca_a_aplicacao_inicial_parte_I.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LLql1V3DvGnA2JnyfdBZrBf53mUN4nAR
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

bank_raw = pd.read_csv("/content/bank-additional-full.csv", sep=';')
bank = bank_raw.copy()

bank_raw.head()

max_age = int(bank.age.max())
min_age = int(bank.age.min())

print(f"Max age: {max_age}")
print(f"Min age: {min_age}")

idades = [min_age, 26]
bank = bank[(bank['age'] >= idades[0]) & (bank['age'] <= idades[1])]

bank_raw_target_perc = bank_raw.y.value_counts(normalize=True).to_frame() * 100
bank_raw_target_perc = bank_raw_target_perc.sort_index()
bank_raw_target_perc

bank_target_perc = bank.y.value_counts(normalize=True).to_frame() * 100
bank_target_perc = bank_target_perc.sort_index()
bank_target_perc

fig, ax = plt.subplots(1, 2, figsize= (5, 3))

sns.barplot(x=bank_raw_target_perc.index, y="proportion", data=bank_raw_target_perc, ax=ax[0])
ax[0].bar_label(ax[0].containers[0])
ax[0].set_title("Dados brutos", fontweight='bold')

sns.barplot(x=bank_target_perc.index, y="proportion", data=bank_target_perc, ax=ax[1])
ax[1].bar_label(ax[1].containers[0])
ax[1].set_title("Dados filtrados", fontweight='bold')

plt.tight_layout()
plt.show()

