# -*- coding: utf-8 -*-
"""sql_m04_tarefa_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bqNfdFuWG8ZyIIrlWYp6hUDHYuHyoXpN
"""

import pandas as pd

"""## Query 1

```sql
SELECT *
FROM transacoes
WHERE valor > 30 AND id_loja = 'magalu';
```
"""

query_01 = pd.read_csv('query_01.csv')
query_01

"""## Query 2

```sql
SELECT *
FROM transacoes
WHERE valor > 30 OR id_loja = 'magalu';
```
"""

query_02 = pd.read_csv('query_02.csv')
query_02

"""## Query 3

```sql
SELECT *
FROM transacoes
WHERE id_loja IN ('magalu','subway') AND valor > 10;
```
"""

query_03 = pd.read_csv('query_03.csv')
query_03

"""## Query 4

```sql
SELECT *
FROM transacoes
WHERE valor BETWEEN 60.0 AND 1000.0;
```
"""

query_04 = pd.read_csv('query_04.csv')
query_04

"""## Query 5

```sql
SELECT *
FROM transacoes
WHERE id_loja LIKE 'mag%'
```
"""

query_05 = pd.read_csv('query_05.csv')
query_05

"""## Query 6

```sql
SELECT *
FROM transacoes
WHERE id_loja LIKE '%sh%'
```
"""

query_06 = pd.read_csv('query_06.csv')
query_06

"""## Query 7

```sql
SELECT id_cliente, id_loja, valor,
CASE
    WHEN valor > 1000 THEN 'Compra com alto valor'
    WHEN valor < 1000 THEN 'Compra com baixo valor'
END
AS classeValor,
CASE
    WHEN id_loja IN ('giraffas','subway')  THEN 'alimentacao'
    WHEN id_loja IN ('magalu','extra') THEN 'variedade'
    WHEN id_loja IN ('postoshell','seveneleven') THEN '24horas'
    ELSE 'outros'
END
AS tipo_compra
FROM transacoes;
```
"""

query_07 = pd.read_csv('query_07.csv')
query_07